import { QuestionDefinition } from "../questionBank";

export const LEVEL_2_QUESTIONS: QuestionDefinition[] = [
  {
    id: "ch-2",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The robotic arm controller prints the binary status word: 00101010.\nConvert this byte to decimal to unlock the servos.",
    answer: "42",
    acceptedAnswers: ["42", "forty two", "forty-two"],
    hints: {
      1: { order: 1, text: "Binary place values from right to left are 1, 2, 4, 8, 16, 32, 64, 128.", penaltySeconds: 15 },
      2: { order: 2, text: "Sum the powers of 2 where the bit is 1: 32 + 8 + 2.", penaltySeconds: 30 },
      3: { order: 3, text: "32 plus 8 is 40. Add 2 to get 42.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-2",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The servo calibration sensor outputs the binary byte: 00110100.\nConvert this byte to decimal to calibrate the motor.",
    answer: "52",
    acceptedAnswers: ["52", "fifty two", "fifty-two"],
    hints: {
      1: { order: 1, text: "Examine bits at positions: 32, 16, and 4.", penaltySeconds: 15 },
      2: { order: 2, text: "Sum the active bits: 32 + 16 + 4.", penaltySeconds: 30 },
      3: { order: 3, text: "32 + 16 = 48, 48 + 4 = 52.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-3",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The actuator telemetry register reads the binary byte: 00011110.\nConvert this byte to decimal.",
    answer: "30",
    acceptedAnswers: ["30", "thirty"],
    hints: {
      1: { order: 1, text: "Active bits are at 16, 8, 4, and 2.", penaltySeconds: 15 },
      2: { order: 2, text: "Sum: 16 + 8 + 4 + 2.", penaltySeconds: 30 },
      3: { order: 3, text: "16 + 8 = 24; 24 + 4 + 2 = 30.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-4",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The sensor relay transmits binary byte: 00001111.\nConvert this nibble combination to decimal.",
    answer: "15",
    acceptedAnswers: ["15", "fifteen"],
    hints: {
      1: { order: 1, text: "The lowest 4 bits are all 1s: 8, 4, 2, 1.", penaltySeconds: 15 },
      2: { order: 2, text: "Sum 8 + 4 + 2 + 1.", penaltySeconds: 30 },
      3: { order: 3, text: "8 + 4 + 2 + 1 = 15.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-5",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The optical encoder reads binary pattern: 00010101.\nConvert this byte to decimal to establish position.",
    answer: "21",
    acceptedAnswers: ["21", "twenty one", "twenty-one"],
    hints: {
      1: { order: 1, text: "Active bit weights are 16, 4, and 1.", penaltySeconds: 15 },
      2: { order: 2, text: "Sum 16 + 4 + 1.", penaltySeconds: 30 },
      3: { order: 3, text: "16 + 4 = 20; 20 + 1 = 21.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-6",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "A motor diagnostic register shows binary byte: 00100001.\nConvert this value to decimal.",
    answer: "33",
    acceptedAnswers: ["33", "thirty three", "thirty-three"],
    hints: {
      1: { order: 1, text: "Bit 5 (32) and Bit 0 (1) are set.", penaltySeconds: 15 },
      2: { order: 2, text: "Sum 32 + 1.", penaltySeconds: 30 },
      3: { order: 3, text: "32 + 1 = 33.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-7",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The power distribution switch reads binary byte: 00111111.\nConvert this byte to decimal.",
    answer: "63",
    acceptedAnswers: ["63", "sixty three", "sixty-three"],
    hints: {
      1: { order: 1, text: "The six lowest bits are all 1: 32 + 16 + 8 + 4 + 2 + 1.", penaltySeconds: 15 },
      2: { order: 2, text: "This is equal to 2^6 - 1.", penaltySeconds: 30 },
      3: { order: 3, text: "64 - 1 = 63.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-8",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "An ultrasonic rangefinder transmits binary byte: 00011000.\nConvert to decimal.",
    answer: "24",
    acceptedAnswers: ["24", "twenty four", "twenty-four"],
    hints: {
      1: { order: 1, text: "The active bits are 16 and 8.", penaltySeconds: 15 },
      2: { order: 2, text: "16 + 8.", penaltySeconds: 30 },
      3: { order: 3, text: "16 + 8 = 24.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-9",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The servo angle sensor reports binary: 00100100.\nConvert this byte to decimal.",
    answer: "36",
    acceptedAnswers: ["36", "thirty six", "thirty-six"],
    hints: {
      1: { order: 1, text: "The active bit positions are 32 and 4.", penaltySeconds: 15 },
      2: { order: 2, text: "Add 32 and 4.", penaltySeconds: 30 },
      3: { order: 3, text: "32 + 4 = 36.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-10",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The gripper pressure controller registers binary: 00101101.\nWhat is its decimal value?",
    answer: "45",
    acceptedAnswers: ["45", "forty five", "forty-five"],
    hints: {
      1: { order: 1, text: "Active bits are 32, 8, 4, and 1.", penaltySeconds: 15 },
      2: { order: 2, text: "Sum: 32 + 8 + 4 + 1.", penaltySeconds: 30 },
      3: { order: 3, text: "40 + 5 = 45.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-11",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The current shunt telemetry displays binary: 00010011.\nConvert this reading to decimal.",
    answer: "19",
    acceptedAnswers: ["19", "nineteen"],
    hints: {
      1: { order: 1, text: "Bits set are 16, 2, and 1.", penaltySeconds: 15 },
      2: { order: 2, text: "16 + 2 + 1.", penaltySeconds: 30 },
      3: { order: 3, text: "16 + 3 = 19.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-12",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "A conveyor tachometer outputs binary: 00011010.\nConvert to decimal.",
    answer: "26",
    acceptedAnswers: ["26", "twenty six", "twenty-six"],
    hints: {
      1: { order: 1, text: "Bit positions are 16, 8, and 2.", penaltySeconds: 15 },
      2: { order: 2, text: "16 + 8 + 2.", penaltySeconds: 30 },
      3: { order: 3, text: "24 + 2 = 26.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-13",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The actuator torque telemetry displays binary: 00111000.\nWhat is this value in decimal?",
    answer: "56",
    acceptedAnswers: ["56", "fifty six", "fifty-six"],
    hints: {
      1: { order: 1, text: "Bits 32, 16, and 8 are high.", penaltySeconds: 15 },
      2: { order: 2, text: "Sum: 32 + 16 + 8.", penaltySeconds: 30 },
      3: { order: 3, text: "48 + 8 = 56.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-14",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The stepper motor driver reports binary step: 00100111.\nConvert to decimal.",
    answer: "39",
    acceptedAnswers: ["39", "thirty nine", "thirty-nine"],
    hints: {
      1: { order: 1, text: "Active bits: 32, 4, 2, and 1.", penaltySeconds: 15 },
      2: { order: 2, text: "32 + 4 + 2 + 1.", penaltySeconds: 30 },
      3: { order: 3, text: "32 + 7 = 39.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-15",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The safety relay status byte reads binary: 00001101.\nConvert to decimal.",
    answer: "13",
    acceptedAnswers: ["13", "thirteen"],
    hints: {
      1: { order: 1, text: "Active bits are 8, 4, and 1.", penaltySeconds: 15 },
      2: { order: 2, text: "8 + 4 + 1.", penaltySeconds: 30 },
      3: { order: 3, text: "12 + 1 = 13.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-16",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The lidar sync word displays binary: 00110011.\nWhat is its decimal value?",
    answer: "51",
    acceptedAnswers: ["51", "fifty one", "fifty-one"],
    hints: {
      1: { order: 1, text: "Active bit weights: 32, 16, 2, and 1.", penaltySeconds: 15 },
      2: { order: 2, text: "32 + 16 + 2 + 1.", penaltySeconds: 30 },
      3: { order: 3, text: "48 + 3 = 51.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-17",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The voltage rail selector outputs binary: 00011100.\nConvert to decimal.",
    answer: "28",
    acceptedAnswers: ["28", "twenty eight", "twenty-eight"],
    hints: {
      1: { order: 1, text: "Bits 16, 8, and 4 are high.", penaltySeconds: 15 },
      2: { order: 2, text: "16 + 8 + 4.", penaltySeconds: 30 },
      3: { order: 3, text: "24 + 4 = 28.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-18",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The payload sensor transmits binary: 00101110.\nConvert to decimal.",
    answer: "46",
    acceptedAnswers: ["46", "forty six", "forty-six"],
    hints: {
      1: { order: 1, text: "Active bits: 32, 8, 4, and 2.", penaltySeconds: 15 },
      2: { order: 2, text: "32 + 8 + 4 + 2.", penaltySeconds: 30 },
      3: { order: 3, text: "40 + 6 = 46.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-19",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The robotic joint pitch sensor outputs binary: 00110110.\nConvert to decimal.",
    answer: "54",
    acceptedAnswers: ["54", "fifty four", "fifty-four"],
    hints: {
      1: { order: 1, text: "Active bits are 32, 16, 4, and 2.", penaltySeconds: 15 },
      2: { order: 2, text: "32 + 16 + 4 + 2.", penaltySeconds: 30 },
      3: { order: 3, text: "48 + 6 = 54.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-20",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "A digital thermometer returns binary reading: 00001110.\nWhat is this in decimal?",
    answer: "14",
    acceptedAnswers: ["14", "fourteen"],
    hints: {
      1: { order: 1, text: "Bits 8, 4, and 2 are high.", penaltySeconds: 15 },
      2: { order: 2, text: "8 + 4 + 2.", penaltySeconds: 30 },
      3: { order: 3, text: "12 + 2 = 14.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-21",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The valve actuation status word is binary: 00100011.\nConvert to decimal.",
    answer: "35",
    acceptedAnswers: ["35", "thirty five", "thirty-five"],
    hints: {
      1: { order: 1, text: "Active bits: 32, 2, and 1.", penaltySeconds: 15 },
      2: { order: 2, text: "32 + 2 + 1.", penaltySeconds: 30 },
      3: { order: 3, text: "32 + 3 = 35.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-22",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The power bus current limit is set to binary: 00010111.\nConvert to decimal.",
    answer: "23",
    acceptedAnswers: ["23", "twenty three", "twenty-three"],
    hints: {
      1: { order: 1, text: "Active bits: 16, 4, 2, and 1.", penaltySeconds: 15 },
      2: { order: 2, text: "16 + 4 + 2 + 1.", penaltySeconds: 30 },
      3: { order: 3, text: "20 + 3 = 23.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-2-23",
    levelId: 2,
    difficulty: "EASY",
    type: "binary",
    category: "Binary Conversion",
    question: "The robotic arm yaw angle registers binary: 00111100.\nConvert to decimal.",
    answer: "60",
    acceptedAnswers: ["60", "sixty"],
    hints: {
      1: { order: 1, text: "Active bits are 32, 16, 8, and 4.", penaltySeconds: 15 },
      2: { order: 2, text: "32 + 16 + 8 + 4.", penaltySeconds: 30 },
      3: { order: 3, text: "48 + 12 = 60.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
];
