import { QuestionDefinition } from "../questionBank";

export const LEVEL_3_QUESTIONS: QuestionDefinition[] = [
  {
    id: "ch-3",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The server diagnostic displays the hexadecimal access code: 3F.\nConvert this hexadecimal value to decimal to unlock the encrypted system.",
    answer: "63",
    acceptedAnswers: ["63", "sixty three", "sixty-three"],
    hints: {
      1: { order: 1, text: "Hexadecimal uses base 16. The high nibble '3' represents 3 * 16.", penaltySeconds: 15 },
      2: { order: 2, text: "'F' in hexadecimal equals 15 in decimal.", penaltySeconds: 30 },
      3: { order: 3, text: "(3 * 16) + 15 = 48 + 15 = 63.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-2",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The kernel stack frame register dumps the hex byte: 4A.\nConvert this byte to decimal to decode the stack address.",
    answer: "74",
    acceptedAnswers: ["74", "seventy four", "seventy-four"],
    hints: {
      1: { order: 1, text: "Multiply the first digit '4' by 16.", penaltySeconds: 15 },
      2: { order: 2, text: "The hex digit 'A' corresponds to decimal 10.", penaltySeconds: 30 },
      3: { order: 3, text: "(4 * 16) + 10 = 64 + 10 = 74.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-3",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The network router logs a checksum byte in hexadecimal: 5C.\nConvert this hexadecimal checksum to decimal.",
    answer: "92",
    acceptedAnswers: ["92", "ninety two", "ninety-two"],
    hints: {
      1: { order: 1, text: "High nibble 5 is worth 5 * 16.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex digit 'C' equals 12 in decimal.", penaltySeconds: 30 },
      3: { order: 3, text: "5 * 16 = 80; 80 + 12 = 92.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-4",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The bootloader debug port outputs the hex byte: 2B.\nConvert this value to decimal.",
    answer: "43",
    acceptedAnswers: ["43", "forty three", "forty-three"],
    hints: {
      1: { order: 1, text: "Multiply 2 by 16.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex digit 'B' equals decimal 11.", penaltySeconds: 30 },
      3: { order: 3, text: "(2 * 16) + 11 = 32 + 11 = 43.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-5",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The memory controller parity register shows hex code: 3D.\nConvert to decimal.",
    answer: "61",
    acceptedAnswers: ["61", "sixty one", "sixty-one"],
    hints: {
      1: { order: 1, text: "High nibble '3' represents 3 * 16.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex digit 'D' is 13.", penaltySeconds: 30 },
      3: { order: 3, text: "48 + 13 = 61.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-6",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "An interrupt vector address is marked as hex: 4F.\nConvert this byte to decimal.",
    answer: "79",
    acceptedAnswers: ["79", "seventy nine", "seventy-nine"],
    hints: {
      1: { order: 1, text: "Calculate 4 * 16.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex digit 'F' equals 15.", penaltySeconds: 30 },
      3: { order: 3, text: "64 + 15 = 79.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-7",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The serial port baud selector indicates hex value: 55.\nConvert to decimal.",
    answer: "85",
    acceptedAnswers: ["85", "eighty five", "eighty-five"],
    hints: {
      1: { order: 1, text: "High nibble is 5 * 16.", penaltySeconds: 15 },
      2: { order: 2, text: "Low nibble is 5.", penaltySeconds: 30 },
      3: { order: 3, text: "80 + 5 = 85.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-8",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "A PCI configuration register shows hex offset: 6B.\nConvert this offset to decimal.",
    answer: "107",
    acceptedAnswers: ["107", "one hundred seven", "one hundred seven"],
    hints: {
      1: { order: 1, text: "Multiply 6 by 16.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'B' is 11.", penaltySeconds: 30 },
      3: { order: 3, text: "96 + 11 = 107.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-9",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The cache line tag reads hex value: 7E.\nConvert to decimal.",
    answer: "126",
    acceptedAnswers: ["126", "one hundred twenty six", "one hundred twenty-six"],
    hints: {
      1: { order: 1, text: "Multiply 7 by 16: 7 * 16 = 112.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'E' is 14.", penaltySeconds: 30 },
      3: { order: 3, text: "112 + 14 = 126.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-10",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The DMA buffer boundary is aligned to hex: 2F.\nConvert this to decimal.",
    answer: "47",
    acceptedAnswers: ["47", "forty seven", "forty-seven"],
    hints: {
      1: { order: 1, text: "2 * 16 = 32.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'F' is 15.", penaltySeconds: 30 },
      3: { order: 3, text: "32 + 15 = 47.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-11",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The power management IC reports telemetry code in hex: 58.\nConvert to decimal.",
    answer: "88",
    acceptedAnswers: ["88", "eighty eight", "eighty-eight"],
    hints: {
      1: { order: 1, text: "5 * 16 = 80.", penaltySeconds: 15 },
      2: { order: 2, text: "Low digit is 8.", penaltySeconds: 30 },
      3: { order: 3, text: "80 + 8 = 88.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-12",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The GPU command queue depth is coded in hex: 64.\nConvert to decimal.",
    answer: "100",
    acceptedAnswers: ["100", "one hundred"],
    hints: {
      1: { order: 1, text: "Calculate 6 * 16.", penaltySeconds: 15 },
      2: { order: 2, text: "6 * 16 = 96.", penaltySeconds: 30 },
      3: { order: 3, text: "96 + 4 = 100.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-13",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The display resolution mode index is hex: 44.\nConvert to decimal.",
    answer: "68",
    acceptedAnswers: ["68", "sixty eight", "sixty-eight"],
    hints: {
      1: { order: 1, text: "4 * 16 = 64.", penaltySeconds: 15 },
      2: { order: 2, text: "Add 4.", penaltySeconds: 30 },
      3: { order: 3, text: "64 + 4 = 68.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-14",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The system thermal threshold register shows hex: 5A.\nConvert to decimal.",
    answer: "90",
    acceptedAnswers: ["90", "ninety"],
    hints: {
      1: { order: 1, text: "5 * 16 = 80.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'A' is 10.", penaltySeconds: 30 },
      3: { order: 3, text: "80 + 10 = 90.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-15",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The BIOS configuration strap reads hex byte: 71.\nConvert to decimal.",
    answer: "113",
    acceptedAnswers: ["113", "one hundred thirteen"],
    hints: {
      1: { order: 1, text: "7 * 16 = 112.", penaltySeconds: 15 },
      2: { order: 2, text: "Add 1.", penaltySeconds: 30 },
      3: { order: 3, text: "112 + 1 = 113.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-16",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The disk controller sector count registers hex: 3E.\nConvert to decimal.",
    answer: "62",
    acceptedAnswers: ["62", "sixty two", "sixty-two"],
    hints: {
      1: { order: 1, text: "3 * 16 = 48.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'E' is 14.", penaltySeconds: 30 },
      3: { order: 3, text: "48 + 14 = 62.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-17",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The watchdog timer countdown register indicates hex: 6F.\nConvert to decimal.",
    answer: "111",
    acceptedAnswers: ["111", "one hundred eleven"],
    hints: {
      1: { order: 1, text: "6 * 16 = 96.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'F' is 15.", penaltySeconds: 30 },
      3: { order: 3, text: "96 + 15 = 111.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-18",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The ethernet PHY register status byte is hex: 4C.\nConvert to decimal.",
    answer: "76",
    acceptedAnswers: ["76", "seventy six", "seventy-six"],
    hints: {
      1: { order: 1, text: "4 * 16 = 64.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'C' is 12.", penaltySeconds: 30 },
      3: { order: 3, text: "64 + 12 = 76.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-19",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The storage block metadata tag is hex: 5E.\nConvert to decimal.",
    answer: "94",
    acceptedAnswers: ["94", "ninety four", "ninety-four"],
    hints: {
      1: { order: 1, text: "5 * 16 = 80.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'E' is 14.", penaltySeconds: 30 },
      3: { order: 3, text: "80 + 14 = 94.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-20",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The keyboard scan code controller yields hex: 7A.\nConvert to decimal.",
    answer: "122",
    acceptedAnswers: ["122", "one hundred twenty two", "one hundred twenty-two"],
    hints: {
      1: { order: 1, text: "7 * 16 = 112.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'A' is 10.", penaltySeconds: 30 },
      3: { order: 3, text: "112 + 10 = 122.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-21",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The real-time clock seconds register reads hex: 2E.\nConvert to decimal.",
    answer: "46",
    acceptedAnswers: ["46", "forty six", "forty-six"],
    hints: {
      1: { order: 1, text: "2 * 16 = 32.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'E' is 14.", penaltySeconds: 30 },
      3: { order: 3, text: "32 + 14 = 46.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-22",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The audio codec sampling divider register reads hex: 3A.\nConvert to decimal.",
    answer: "58",
    acceptedAnswers: ["58", "fifty eight", "fifty-eight"],
    hints: {
      1: { order: 1, text: "3 * 16 = 48.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'A' is 10.", penaltySeconds: 30 },
      3: { order: 3, text: "48 + 10 = 58.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-3-23",
    levelId: 3,
    difficulty: "MEDIUM",
    type: "hexadecimal",
    category: "Hexadecimal Conversion",
    question: "The fan speed PWM duty cycle register is hex: 6A.\nConvert to decimal.",
    answer: "106",
    acceptedAnswers: ["106", "one hundred six"],
    hints: {
      1: { order: 1, text: "6 * 16 = 96.", penaltySeconds: 15 },
      2: { order: 2, text: "Hex 'A' is 10.", penaltySeconds: 30 },
      3: { order: 3, text: "96 + 10 = 106.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
];
