import { QuestionDefinition } from "../questionBank";

export const LEVEL_6_QUESTIONS: QuestionDefinition[] = [
  {
    id: "ch-6",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The digital locker lock security chip executes the C expression:\n(1 << 6)\nEvaluate this bitwise left-shift expression as a decimal integer.",
    answer: "64",
    acceptedAnswers: ["64", "sixty four", "sixty-four"],
    hints: {
      1: { order: 1, text: "A left shift of 1 by k positions computes 2 to the power of k.", penaltySeconds: 15 },
      2: { order: 2, text: "Calculate 2^6.", penaltySeconds: 30 },
      3: { order: 3, text: "2^6 = 64.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-2",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The memory protection unit evaluates the bitwise expression:\n(1 << 7)\nDetermine the resulting decimal value.",
    answer: "128",
    acceptedAnswers: ["128", "one hundred twenty eight", "one hundred twenty-eight"],
    hints: {
      1: { order: 1, text: "Shifting 1 left by 7 bits computes 2^7.", penaltySeconds: 15 },
      2: { order: 2, text: "Calculate 2 to the power of 7.", penaltySeconds: 30 },
      3: { order: 3, text: "2^7 = 128.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-3",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The bus arbitration circuit computes the bitwise expression:\n(3 << 5)\nEvaluate this left-shift expression as a decimal integer.",
    answer: "96",
    acceptedAnswers: ["96", "ninety six", "ninety-six"],
    hints: {
      1: { order: 1, text: "Left-shifting by 5 multiplies the operand by 2^5 = 32.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply 3 by 32.", penaltySeconds: 30 },
      3: { order: 3, text: "3 * 32 = 96.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-4",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The cryptographic hardware accelerator computes:\n(1 << 5)\nEvaluate this bitwise left-shift as a decimal integer.",
    answer: "32",
    acceptedAnswers: ["32", "thirty two", "thirty-two"],
    hints: {
      1: { order: 1, text: "A left shift of 1 by 5 positions is 2^5.", penaltySeconds: 15 },
      2: { order: 2, text: "2^5 = 32.", penaltySeconds: 30 },
      3: { order: 3, text: "Result is 32.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-5",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The page table offset generator calculates:\n(1 << 8)\nEvaluate this expression in decimal.",
    answer: "256",
    acceptedAnswers: ["256", "two hundred fifty six", "two hundred fifty-six"],
    hints: {
      1: { order: 1, text: "Left shift by 8 multiplies by 2^8.", penaltySeconds: 15 },
      2: { order: 2, text: "Calculate 2 to the power of 8.", penaltySeconds: 30 },
      3: { order: 3, text: "2^8 = 256.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-6",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The peripheral bus clock divider computes:\n(5 << 4)\nWhat is the decimal result of this bitwise operation?",
    answer: "80",
    acceptedAnswers: ["80", "eighty"],
    hints: {
      1: { order: 1, text: "Shifting left by 4 multiplies by 16.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply 5 by 16.", penaltySeconds: 30 },
      3: { order: 3, text: "5 * 16 = 80.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-7",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The vector math coprocessor evaluates:\n(7 << 3)\nCompute the decimal output.",
    answer: "56",
    acceptedAnswers: ["56", "fifty six", "fifty-six"],
    hints: {
      1: { order: 1, text: "Left shifting by 3 multiplies by 2^3 = 8.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply 7 by 8.", penaltySeconds: 30 },
      3: { order: 3, text: "7 * 8 = 56.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-8",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The ring buffer mask computation evaluates:\n(9 << 3)\nDetermine the decimal value.",
    answer: "72",
    acceptedAnswers: ["72", "seventy two", "seventy-two"],
    hints: {
      1: { order: 1, text: "Left shift by 3 multiplies by 8.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply 9 by 8.", penaltySeconds: 30 },
      3: { order: 3, text: "9 * 8 = 72.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-9",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The register right-shift circuit executes:\n(255 >> 3)\nEvaluate this unsigned bitwise right-shift in decimal.",
    answer: "31",
    acceptedAnswers: ["31", "thirty one", "thirty-one"],
    hints: {
      1: { order: 1, text: "Right shifting by 3 performs integer division by 2^3 = 8.", penaltySeconds: 15 },
      2: { order: 2, text: "Floor(255 / 8).", penaltySeconds: 30 },
      3: { order: 3, text: "255 / 8 = 31.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-10",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "An ALU barrel shifter computes:\n(255 >> 4)\nWhat is the resulting decimal integer?",
    answer: "15",
    acceptedAnswers: ["15", "fifteen"],
    hints: {
      1: { order: 1, text: "Shifting right by 4 divides by 16.", penaltySeconds: 15 },
      2: { order: 2, text: "Floor(255 / 16).", penaltySeconds: 30 },
      3: { order: 3, text: "255 / 16 = 15.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-11",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The DMA address alignment shifter computes:\n(192 >> 2)\nDetermine the decimal value.",
    answer: "48",
    acceptedAnswers: ["48", "forty eight", "forty-eight"],
    hints: {
      1: { order: 1, text: "Right-shifting by 2 divides by 4.", penaltySeconds: 15 },
      2: { order: 2, text: "192 / 4.", penaltySeconds: 30 },
      3: { order: 3, text: "192 / 4 = 48.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-12",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The raster scan line multiplier evaluates:\n(11 << 3)\nCalculate the decimal output.",
    answer: "88",
    acceptedAnswers: ["88", "eighty eight", "eighty-eight"],
    hints: {
      1: { order: 1, text: "Shift left by 3 multiplies by 8.", penaltySeconds: 15 },
      2: { order: 2, text: "11 * 8.", penaltySeconds: 30 },
      3: { order: 3, text: "11 * 8 = 88.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-13",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The memory bank index expression computes:\n(3 << 6)\nEvaluate as a decimal integer.",
    answer: "192",
    acceptedAnswers: ["192", "one hundred ninety two", "one hundred ninety-two"],
    hints: {
      1: { order: 1, text: "Left shift by 6 multiplies by 2^6 = 64.", penaltySeconds: 15 },
      2: { order: 2, text: "3 * 64.", penaltySeconds: 30 },
      3: { order: 3, text: "3 * 64 = 192.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-14",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The interrupt mask circuit executes bitwise AND:\n(63 & 45)\nEvaluate this bitwise AND expression in decimal.",
    answer: "45",
    acceptedAnswers: ["45", "forty five", "forty-five"],
    hints: {
      1: { order: 1, text: "63 in binary is 00111111 (the lowest 6 bits are all 1).", penaltySeconds: 15 },
      2: { order: 2, text: "Since 45 is less than 64, all of its active bits are within those 6 bits.", penaltySeconds: 30 },
      3: { order: 3, text: "Bitwise AND with a mask of all 1s preserves the value: 45.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-15",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The parity flip logic computes bitwise XOR:\n(15 ^ 27)\nEvaluate this XOR expression in decimal.",
    answer: "20",
    acceptedAnswers: ["20", "twenty"],
    hints: {
      1: { order: 1, text: "Convert to binary: 15 is 00001111, 27 is 00011011.", penaltySeconds: 15 },
      2: { order: 2, text: "XOR returns 1 where bits differ: 00010100.", penaltySeconds: 30 },
      3: { order: 3, text: "00010100 in decimal is 16 + 4 = 20.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-16",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The timer frequency prescaler computes:\n(120 >> 1)\nWhat is the decimal result?",
    answer: "60",
    acceptedAnswers: ["60", "sixty"],
    hints: {
      1: { order: 1, text: "Right shifting by 1 is equivalent to dividing by 2.", penaltySeconds: 15 },
      2: { order: 2, text: "120 / 2.", penaltySeconds: 30 },
      3: { order: 3, text: "120 / 2 = 60.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-17",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The hardware pixel blending unit computes:\n(7 << 4)\nDetermine the decimal value.",
    answer: "112",
    acceptedAnswers: ["112", "one hundred twelve"],
    hints: {
      1: { order: 1, text: "Left shift by 4 multiplies by 16.", penaltySeconds: 15 },
      2: { order: 2, text: "7 * 16.", penaltySeconds: 30 },
      3: { order: 3, text: "7 * 16 = 112.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-18",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The sector offset logic computes:\n(13 << 2)\nWhat is the decimal result?",
    answer: "52",
    acceptedAnswers: ["52", "fifty two", "fifty-two"],
    hints: {
      1: { order: 1, text: "Left shifting by 2 multiplies by 4.", penaltySeconds: 15 },
      2: { order: 2, text: "13 * 4.", penaltySeconds: 30 },
      3: { order: 3, text: "13 * 4 = 52.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-19",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The bitwise filter circuit performs AND masking:\n(127 & 85)\nEvaluate as a decimal integer.",
    answer: "85",
    acceptedAnswers: ["85", "eighty five", "eighty-five"],
    hints: {
      1: { order: 1, text: "127 is 01111111 in binary (7 consecutive 1s).", penaltySeconds: 15 },
      2: { order: 2, text: "85 is 01010101 in binary, which fits completely under the 7-bit mask.", penaltySeconds: 30 },
      3: { order: 3, text: "The result is 85.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-20",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The bus rate divider executes:\n(224 >> 2)\nCalculate the decimal integer.",
    answer: "56",
    acceptedAnswers: ["56", "fifty six", "fifty-six"],
    hints: {
      1: { order: 1, text: "Right shifting by 2 divides by 4.", penaltySeconds: 15 },
      2: { order: 2, text: "224 / 4.", penaltySeconds: 30 },
      3: { order: 3, text: "224 / 4 = 56.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-21",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The network packet header offset calculates:\n(17 << 2)\nDetermine the decimal value.",
    answer: "68",
    acceptedAnswers: ["68", "sixty eight", "sixty-eight"],
    hints: {
      1: { order: 1, text: "Left shift by 2 multiplies by 4.", penaltySeconds: 15 },
      2: { order: 2, text: "17 * 4.", penaltySeconds: 30 },
      3: { order: 3, text: "17 * 4 = 68.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-22",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The error-correcting code syndrome evaluator computes:\n(51 ^ 20)\nEvaluate this bitwise XOR operation in decimal.",
    answer: "39",
    acceptedAnswers: ["39", "thirty nine", "thirty-nine"],
    hints: {
      1: { order: 1, text: "51 in binary is 00110011; 20 is 00010100.", penaltySeconds: 15 },
      2: { order: 2, text: "Bitwise XOR yields 00100111.", penaltySeconds: 30 },
      3: { order: 3, text: "32 + 4 + 2 + 1 = 39.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-6-23",
    levelId: 6,
    difficulty: "HARD",
    type: "bitwise",
    category: "Bitwise Operators",
    question: "The hardware frame buffer indexer calculates:\n(21 << 2)\nEvaluate as a decimal integer.",
    answer: "84",
    acceptedAnswers: ["84", "eighty four", "eighty-four"],
    hints: {
      1: { order: 1, text: "Multiply 21 by 4.", penaltySeconds: 15 },
      2: { order: 2, text: "21 * 4.", penaltySeconds: 30 },
      3: { order: 3, text: "21 * 4 = 84.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
];
