import { QuestionDefinition } from "../questionBank";

export const LEVEL_1_QUESTIONS: QuestionDefinition[] = [
  {
    id: "ch-1",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "The archive terminal prints a sequence: 2, 3, 5, 9, 17, 33, ?\nWhat is the next number in this sequence?",
    answer: "65",
    acceptedAnswers: ["65", "sixty five", "sixty-five"],
    hints: {
      1: { order: 1, text: "The pattern doubles each number and subtracts one.", penaltySeconds: 15 },
      2: { order: 2, text: "Look at how each number is generated from the previous number: (33 * 2) - 1.", penaltySeconds: 30 },
      3: { order: 3, text: "Multiply 33 by 2 to get 66, then subtract 1.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-2",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "An encrypted catalogue terminal prints the sequence: 3, 6, 12, 24, 48, ?\nEnter the next integer in the series.",
    answer: "96",
    acceptedAnswers: ["96", "ninety six", "ninety-six"],
    hints: {
      1: { order: 1, text: "Each number in the sequence is multiplied by 2.", penaltySeconds: 15 },
      2: { order: 2, text: "Calculate 48 multiplied by 2.", penaltySeconds: 30 },
      3: { order: 3, text: "48 * 2 = 96.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-3",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "The reading hall terminal displays an arithmetic progression: 7, 14, 21, 28, 35, ?\nEnter the next number.",
    answer: "42",
    acceptedAnswers: ["42", "forty two", "forty-two"],
    hints: {
      1: { order: 1, text: "Look at the common difference between successive terms.", penaltySeconds: 15 },
      2: { order: 2, text: "Each step adds 7 to the previous value.", penaltySeconds: 30 },
      3: { order: 3, text: "35 + 7 = 42.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-4",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "The digital catalog displays a geometric sequence: 5, 10, 20, 40, 80, ?\nWhat is the next number?",
    answer: "160",
    acceptedAnswers: ["160", "one hundred sixty"],
    hints: {
      1: { order: 1, text: "Each term is multiplied by 2.", penaltySeconds: 15 },
      2: { order: 2, text: "Double the last term: 80 * 2.", penaltySeconds: 30 },
      3: { order: 3, text: "80 * 2 = 160.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-5",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "A terminal shows perfect squares: 1, 4, 9, 16, 25, 36, ?\nEnter the next square in the series.",
    answer: "49",
    acceptedAnswers: ["49", "forty nine", "forty-nine"],
    hints: {
      1: { order: 1, text: "These are squares of consecutive integers: 1², 2², 3², 4², 5², 6².", penaltySeconds: 15 },
      2: { order: 2, text: "Calculate 7 squared.", penaltySeconds: 30 },
      3: { order: 3, text: "7 * 7 = 49.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-6",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "The logic sequence reads: 2, 6, 12, 20, 30, 42, ?\nFind the next integer.",
    answer: "56",
    acceptedAnswers: ["56", "fifty six", "fifty-six"],
    hints: {
      1: { order: 1, text: "Look at the differences: +4, +6, +8, +10, +12.", penaltySeconds: 15 },
      2: { order: 2, text: "The next difference to add is 14.", penaltySeconds: 30 },
      3: { order: 3, text: "42 + 14 = 56.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-7",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "An arithmetic decrement pattern shows: 100, 92, 84, 76, 68, ?\nEnter the next value in the countdown.",
    answer: "60",
    acceptedAnswers: ["60", "sixty"],
    hints: {
      1: { order: 1, text: "Each step subtracts a constant value.", penaltySeconds: 15 },
      2: { order: 2, text: "Subtract 8 from the last number.", penaltySeconds: 30 },
      3: { order: 3, text: "68 - 8 = 60.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-8",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "The diagnostic register prints: 1, 1, 2, 3, 5, 8, 13, ?\nDetermine the next number in this Fibonacci series.",
    answer: "21",
    acceptedAnswers: ["21", "twenty one", "twenty-one"],
    hints: {
      1: { order: 1, text: "Each term is the sum of the two preceding terms.", penaltySeconds: 15 },
      2: { order: 2, text: "Add 8 and 13 together.", penaltySeconds: 30 },
      3: { order: 3, text: "8 + 13 = 21.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-9",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "A progression formula generates: 4, 9, 19, 39, 79, ?\nWhat is the next number?",
    answer: "159",
    acceptedAnswers: ["159", "one hundred fifty nine", "one hundred fifty-nine"],
    hints: {
      1: { order: 1, text: "Each term is obtained by multiplying by 2 and adding 1.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply 79 by 2, then add 1.", penaltySeconds: 30 },
      3: { order: 3, text: "79 * 2 = 158; 158 + 1 = 159.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-10",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "The memory address bus powers up with: 2, 4, 8, 16, 32, 64, ?\nEnter the next power of two.",
    answer: "128",
    acceptedAnswers: ["128", "one hundred twenty eight", "one hundred twenty-eight"],
    hints: {
      1: { order: 1, text: "Powers of two: 2^1, 2^2, 2^3, 2^4, 2^5, 2^6.", penaltySeconds: 15 },
      2: { order: 2, text: "Double 64.", penaltySeconds: 30 },
      3: { order: 3, text: "64 * 2 = 128.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-11",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "A repeater signal transmits: 11, 22, 33, 44, 55, ?\nWhat is the next integer?",
    answer: "66",
    acceptedAnswers: ["66", "sixty six", "sixty-six"],
    hints: {
      1: { order: 1, text: "This is a simple arithmetic series with step 11.", penaltySeconds: 15 },
      2: { order: 2, text: "Add 11 to 55.", penaltySeconds: 30 },
      3: { order: 3, text: "55 + 11 = 66.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-12",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "A decaying signal trace reads: 81, 27, 9, 3, ?\nEnter the next value in the decay curve.",
    answer: "1",
    acceptedAnswers: ["1", "one"],
    hints: {
      1: { order: 1, text: "Each step divides the previous number by 3.", penaltySeconds: 15 },
      2: { order: 2, text: "Divide 3 by 3.", penaltySeconds: 30 },
      3: { order: 3, text: "3 / 3 = 1.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-13",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "A delta-step series displays: 4, 7, 12, 19, 28, ?\nWhat is the next number?",
    answer: "39",
    acceptedAnswers: ["39", "thirty nine", "thirty-nine"],
    hints: {
      1: { order: 1, text: "The increments are successive odd numbers: +3, +5, +7, +9.", penaltySeconds: 15 },
      2: { order: 2, text: "The next increment is +11.", penaltySeconds: 30 },
      3: { order: 3, text: "28 + 11 = 39.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-14",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "An alternating sequence produces: 10, 20, 25, 50, 55, 110, ?\nDetermine the next number.",
    answer: "115",
    acceptedAnswers: ["115", "one hundred fifteen"],
    hints: {
      1: { order: 1, text: "The operations alternate: multiply by 2, then add 5.", penaltySeconds: 15 },
      2: { order: 2, text: "After multiplying 55 by 2 to get 110, the next step is adding 5.", penaltySeconds: 30 },
      3: { order: 3, text: "110 + 5 = 115.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-15",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "A cubic expansion registers: 1, 8, 27, 64, ?\nWhat is the next perfect cube in the series?",
    answer: "125",
    acceptedAnswers: ["125", "one hundred twenty five", "one hundred twenty-five"],
    hints: {
      1: { order: 1, text: "Cubes of consecutive numbers: 1³, 2³, 3³, 4³.", penaltySeconds: 15 },
      2: { order: 2, text: "Calculate 5 cubed: 5 * 5 * 5.", penaltySeconds: 30 },
      3: { order: 3, text: "5 * 5 * 5 = 125.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-16",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "A squared difference pattern reads: 2, 3, 7, 16, 32, ?\nFind the next integer.",
    answer: "57",
    acceptedAnswers: ["57", "fifty seven", "fifty-seven"],
    hints: {
      1: { order: 1, text: "The differences are squares: +1² (1), +2² (4), +3² (9), +4² (16).", penaltySeconds: 15 },
      2: { order: 2, text: "Add 5² (25) to 32.", penaltySeconds: 30 },
      3: { order: 3, text: "32 + 25 = 57.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-17",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "The power reserve decreases uniformly: 50, 45, 40, 35, 30, ?\nWhat is the next number?",
    answer: "25",
    acceptedAnswers: ["25", "twenty five", "twenty-five"],
    hints: {
      1: { order: 1, text: "Each step subtracts 5.", penaltySeconds: 15 },
      2: { order: 2, text: "Subtract 5 from 30.", penaltySeconds: 30 },
      3: { order: 3, text: "30 - 5 = 25.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-18",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "A telemetry clock counts in multiples of six: 6, 12, 18, 24, 30, ?\nWhat is the next multiple?",
    answer: "36",
    acceptedAnswers: ["36", "thirty six", "thirty-six"],
    hints: {
      1: { order: 1, text: "Add 6 to the previous value.", penaltySeconds: 15 },
      2: { order: 2, text: "30 + 6.", penaltySeconds: 30 },
      3: { order: 3, text: "30 + 6 = 36.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-19",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "An incremental step sequence registers: 1, 2, 4, 7, 11, 16, ?\nEnter the next integer.",
    answer: "22",
    acceptedAnswers: ["22", "twenty two", "twenty-two"],
    hints: {
      1: { order: 1, text: "The difference increases by 1 each step: +1, +2, +3, +4, +5.", penaltySeconds: 15 },
      2: { order: 2, text: "Add 6 to 16.", penaltySeconds: 30 },
      3: { order: 3, text: "16 + 6 = 22.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-20",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "An accelerated decrement series prints: 70, 68, 64, 58, 50, ?\nWhat is the next number?",
    answer: "40",
    acceptedAnswers: ["40", "forty"],
    hints: {
      1: { order: 1, text: "Subtractions increase by 2 each time: -2, -4, -6, -8.", penaltySeconds: 15 },
      2: { order: 2, text: "Subtract 10 from 50.", penaltySeconds: 30 },
      3: { order: 3, text: "50 - 10 = 40.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-21",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "A tripling series displays: 3, 9, 27, 81, ?\nEnter the next power of three.",
    answer: "243",
    acceptedAnswers: ["243", "two hundred forty three", "two hundred forty-three"],
    hints: {
      1: { order: 1, text: "Multiply each term by 3.", penaltySeconds: 15 },
      2: { order: 2, text: "Calculate 81 * 3.", penaltySeconds: 30 },
      3: { order: 3, text: "81 * 3 = 243.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-22",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "A sensor bus samples data every 15 intervals: 15, 30, 45, 60, 75, ?\nWhat is the next sample index?",
    answer: "90",
    acceptedAnswers: ["90", "ninety"],
    hints: {
      1: { order: 1, text: "Common difference is 15.", penaltySeconds: 15 },
      2: { order: 2, text: "75 + 15.", penaltySeconds: 30 },
      3: { order: 3, text: "75 + 15 = 90.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-1-23",
    levelId: 1,
    difficulty: "EASY",
    type: "logic",
    category: "Number Patterns",
    question: "A calibration step series reads: 14, 28, 42, 56, ?\nDetermine the next number in the sequence.",
    answer: "70",
    acceptedAnswers: ["70", "seventy"],
    hints: {
      1: { order: 1, text: "Each step adds 14.", penaltySeconds: 15 },
      2: { order: 2, text: "56 + 14.", penaltySeconds: 30 },
      3: { order: 3, text: "56 + 14 = 70.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
];
