import { QuestionDefinition } from "../questionBank";

export const LEVEL_8_QUESTIONS: QuestionDefinition[] = [
  {
    id: "ch-8",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "The surveyor's stone marker has an inscription: 2^7 - 1.\nEvaluate this Mersenne expression to determine the boundary calibration offset.",
    answer: "127",
    acceptedAnswers: ["127", "one hundred twenty seven", "one hundred twenty-seven"],
    hints: {
      1: { order: 1, text: "Calculate 2 raised to the 7th power.", penaltySeconds: 15 },
      2: { order: 2, text: "2^7 = 128.", penaltySeconds: 30 },
      3: { order: 3, text: "128 - 1 = 127.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-2",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A triangular garden plot has perpendicular surveyor legs of 39 meters and 52 meters, with a hypotenuse of 65 meters.\nCalculate the total perimeter in meters.",
    answer: "156",
    acceptedAnswers: ["156", "156m", "156 meters", "one hundred fifty six"],
    hints: {
      1: { order: 1, text: "Perimeter is the sum of all three outer boundary sides.", penaltySeconds: 15 },
      2: { order: 2, text: "Sum 39 + 52 + 65.", penaltySeconds: 30 },
      3: { order: 3, text: "39 + 52 = 91; 91 + 65 = 156.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-3",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A circular garden fountain has a radius r = 7 meters.\nUsing π = 22/7, calculate the circumference in meters (C = 2 * π * r).",
    answer: "44",
    acceptedAnswers: ["44", "44m", "44 meters", "forty four"],
    hints: {
      1: { order: 1, text: "Circumference formula: C = 2 * (22/7) * 7.", penaltySeconds: 15 },
      2: { order: 2, text: "The 7 in the denominator cancels with the radius 7.", penaltySeconds: 30 },
      3: { order: 3, text: "2 * 22 = 44.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-4",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "Calculate the straight-line distance from origin (0, 0) to waypoint (24, 7) in meters.",
    answer: "25",
    acceptedAnswers: ["25", "25m", "25 meters", "twenty five"],
    hints: {
      1: { order: 1, text: "Distance formula: d = sqrt(x² + y²).", penaltySeconds: 15 },
      2: { order: 2, text: "24² + 7² = 576 + 49 = 625.", penaltySeconds: 30 },
      3: { order: 3, text: "sqrt(625) = 25.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-5",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "Calculate the Euclidean distance from origin (0, 0) to beacon coordinates (12, 16) in meters.",
    answer: "20",
    acceptedAnswers: ["20", "20m", "20 meters", "twenty"],
    hints: {
      1: { order: 1, text: "d = sqrt(12² + 16²).", penaltySeconds: 15 },
      2: { order: 2, text: "144 + 256 = 400.", penaltySeconds: 30 },
      3: { order: 3, text: "sqrt(400) = 20.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-6",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A rectangular plot has width 15 meters and length 25 meters.\nCalculate its total area in square meters.",
    answer: "375",
    acceptedAnswers: ["375", "375 sqm", "three hundred seventy five"],
    hints: {
      1: { order: 1, text: "Area = width * length.", penaltySeconds: 15 },
      2: { order: 2, text: "15 * 25.", penaltySeconds: 30 },
      3: { order: 3, text: "15 * 25 = 375.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-7",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A perimeter boundary has width 20 meters and length 35 meters.\nCalculate its total perimeter in meters (2 * [w + l]).",
    answer: "110",
    acceptedAnswers: ["110", "110m", "one hundred ten"],
    hints: {
      1: { order: 1, text: "Perimeter = 2 * (length + width).", penaltySeconds: 15 },
      2: { order: 2, text: "2 * (20 + 35) = 2 * 55.", penaltySeconds: 30 },
      3: { order: 3, text: "2 * 55 = 110.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-8",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "Evaluate the Mersenne number formula: 2^6 - 1.",
    answer: "63",
    acceptedAnswers: ["63", "sixty three", "sixty-three"],
    hints: {
      1: { order: 1, text: "Calculate 2^6.", penaltySeconds: 15 },
      2: { order: 2, text: "2^6 = 64.", penaltySeconds: 30 },
      3: { order: 3, text: "64 - 1 = 63.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-9",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "Evaluate the Mersenne prime expression: 2^8 - 1.",
    answer: "255",
    acceptedAnswers: ["255", "two hundred fifty five", "two hundred fifty-five"],
    hints: {
      1: { order: 1, text: "2^8 = 256.", penaltySeconds: 15 },
      2: { order: 2, text: "Subtract 1.", penaltySeconds: 30 },
      3: { order: 3, text: "256 - 1 = 255.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-10",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A circular plaza has radius r = 14 meters.\nUsing π = 22/7, calculate the outer circumference in meters.",
    answer: "88",
    acceptedAnswers: ["88", "88m", "eighty eight", "eighty-eight"],
    hints: {
      1: { order: 1, text: "C = 2 * (22/7) * 14.", penaltySeconds: 15 },
      2: { order: 2, text: "14 / 7 = 2. C = 2 * 22 * 2.", penaltySeconds: 30 },
      3: { order: 3, text: "44 * 2 = 88.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-11",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A circular perimeter boundary has radius r = 21 meters.\nUsing π = 22/7, determine its circumference in meters.",
    answer: "132",
    acceptedAnswers: ["132", "132m", "one hundred thirty two"],
    hints: {
      1: { order: 1, text: "C = 2 * (22/7) * 21.", penaltySeconds: 15 },
      2: { order: 2, text: "21 / 7 = 3. C = 2 * 22 * 3.", penaltySeconds: 30 },
      3: { order: 3, text: "44 * 3 = 132.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-12",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A right triangle has legs of length 9 meters and 12 meters.\nCalculate the hypotenuse length in meters.",
    answer: "15",
    acceptedAnswers: ["15", "15m", "fifteen"],
    hints: {
      1: { order: 1, text: "Pythagorean theorem: c = sqrt(a² + b²).", penaltySeconds: 15 },
      2: { order: 2, text: "9² + 12² = 81 + 144 = 225.", penaltySeconds: 30 },
      3: { order: 3, text: "sqrt(225) = 15.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-13",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A surveyor triangle has perpendicular legs of 20 meters and 21 meters.\nCalculate the hypotenuse in meters.",
    answer: "29",
    acceptedAnswers: ["29", "29m", "twenty nine", "twenty-nine"],
    hints: {
      1: { order: 1, text: "c = sqrt(20² + 21²).", penaltySeconds: 15 },
      2: { order: 2, text: "400 + 441 = 841.", penaltySeconds: 30 },
      3: { order: 3, text: "sqrt(841) = 29.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-14",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A triangular plot has boundary lengths 28 meters, 32 meters, and 40 meters.\nWhat is its total perimeter in meters?",
    answer: "100",
    acceptedAnswers: ["100", "100m", "one hundred"],
    hints: {
      1: { order: 1, text: "Perimeter = sum of sides.", penaltySeconds: 15 },
      2: { order: 2, text: "28 + 32 + 40.", penaltySeconds: 30 },
      3: { order: 3, text: "60 + 40 = 100.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-15",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A square sensor array covers a total area of 169 square meters.\nWhat is the length of one side in meters?",
    answer: "13",
    acceptedAnswers: ["13", "13m", "thirteen"],
    hints: {
      1: { order: 1, text: "Side length is the square root of the area.", penaltySeconds: 15 },
      2: { order: 2, text: "Find sqrt(169).", penaltySeconds: 30 },
      3: { order: 3, text: "sqrt(169) = 13.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-16",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A square pavilion plot has an area of 225 square meters.\nCalculate the side length in meters.",
    answer: "15",
    acceptedAnswers: ["15", "15m", "fifteen"],
    hints: {
      1: { order: 1, text: "Side = sqrt(Area).", penaltySeconds: 15 },
      2: { order: 2, text: "sqrt(225).", penaltySeconds: 30 },
      3: { order: 3, text: "sqrt(225) = 15.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-17",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "The modular grid calibration computes: 125 mod 12.\nWhat is the remainder?",
    answer: "5",
    acceptedAnswers: ["5", "five"],
    hints: {
      1: { order: 1, text: "Divide 125 by 12 and find the integer remainder.", penaltySeconds: 15 },
      2: { order: 2, text: "12 * 10 = 120.", penaltySeconds: 30 },
      3: { order: 3, text: "125 - 120 = 5.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-18",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "The surveyor coordinate hash evaluates: 250 mod 16.\nCalculate the remainder.",
    answer: "10",
    acceptedAnswers: ["10", "ten"],
    hints: {
      1: { order: 1, text: "Find the remainder of 250 divided by 16.", penaltySeconds: 15 },
      2: { order: 2, text: "16 * 15 = 240.", penaltySeconds: 30 },
      3: { order: 3, text: "250 - 240 = 10.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-19",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "Calculate the distance between points (1, 1) and (10, 13) in meters.",
    answer: "15",
    acceptedAnswers: ["15", "15m", "fifteen"],
    hints: {
      1: { order: 1, text: "dx = 10 - 1 = 9; dy = 13 - 1 = 12.", penaltySeconds: 15 },
      2: { order: 2, text: "d = sqrt(9² + 12²) = sqrt(81 + 144).", penaltySeconds: 30 },
      3: { order: 3, text: "sqrt(225) = 15.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-20",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A right triangle has side lengths of 15, 20, and 25 meters.\nWhat is its total perimeter in meters?",
    answer: "60",
    acceptedAnswers: ["60", "60m", "sixty"],
    hints: {
      1: { order: 1, text: "Sum all three sides: 15 + 20 + 25.", penaltySeconds: 15 },
      2: { order: 2, text: "35 + 25.", penaltySeconds: 30 },
      3: { order: 3, text: "35 + 25 = 60.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-21",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "Evaluate the 5th Mersenne number: 2^5 - 1.",
    answer: "31",
    acceptedAnswers: ["31", "thirty one", "thirty-one"],
    hints: {
      1: { order: 1, text: "2^5 = 32.", penaltySeconds: 15 },
      2: { order: 2, text: "Subtract 1 from 32.", penaltySeconds: 30 },
      3: { order: 3, text: "32 - 1 = 31.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-22",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A circular garden pond has a diameter of 28 meters.\nWhat is its radius in meters?",
    answer: "14",
    acceptedAnswers: ["14", "14m", "fourteen"],
    hints: {
      1: { order: 1, text: "Radius is half of diameter: r = d / 2.", penaltySeconds: 15 },
      2: { order: 2, text: "28 / 2.", penaltySeconds: 30 },
      3: { order: 3, text: "28 / 2 = 14.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-8-23",
    levelId: 8,
    difficulty: "HARD",
    type: "geometry",
    category: "Surveyor Mathematics",
    question: "A rectangular perimeter is 80 meters with a length of 25 meters.\nWhat is its width in meters?",
    answer: "15",
    acceptedAnswers: ["15", "15m", "fifteen"],
    hints: {
      1: { order: 1, text: "Perimeter = 2 * (length + width). 80 / 2 = 40.", penaltySeconds: 15 },
      2: { order: 2, text: "width = 40 - length = 40 - 25.", penaltySeconds: 30 },
      3: { order: 3, text: "40 - 25 = 15.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
];
