import { QuestionDefinition } from "../questionBank";

export const LEVEL_5_QUESTIONS: QuestionDefinition[] = [
  {
    id: "ch-5",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A card taped beneath the table bears an encrypted ingredient:\n'LAST'\nUnscramble this 4-letter anagram to reveal the primary kitchen seasoning.",
    answer: "salt",
    acceptedAnswers: ["salt", "salt.", "table salt"],
    hints: {
      1: { order: 1, text: "The letters can be rearranged to name a white crystal mineral used in cooking.", penaltySeconds: 15 },
      2: { order: 2, text: "It begins with the letter S.", penaltySeconds: 30 },
      3: { order: 3, text: "S-A-L-T.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-2",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A chef's ciphered inventory slip reads:\n'REPEPP'\nUnscramble this 6-letter anagram to reveal the common pungent table spice.",
    answer: "pepper",
    acceptedAnswers: ["pepper", "black pepper"],
    hints: {
      1: { order: 1, text: "This spice commonly pairs with salt on dining tables.", penaltySeconds: 15 },
      2: { order: 2, text: "It begins with P and ends with R.", penaltySeconds: 30 },
      3: { order: 3, text: "P-E-P-P-E-R.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-3",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A pantry manifest cipher reads:\n'RAGUS'\nUnscramble this 5-letter anagram to reveal the sweet baking carbohydrate.",
    answer: "sugar",
    acceptedAnswers: ["sugar", "white sugar"],
    hints: {
      1: { order: 1, text: "A sweet crystalline substance extracted from cane or beets.", penaltySeconds: 15 },
      2: { order: 2, text: "It begins with S and ends with R.", penaltySeconds: 30 },
      3: { order: 3, text: "S-U-G-A-R.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-4",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A cold-storage label bears an anagram:\n'TBUETR'\nUnscramble this 6-letter word to identify the common dairy spread.",
    answer: "butter",
    acceptedAnswers: ["butter"],
    hints: {
      1: { order: 1, text: "A solid dairy spread churned from cream.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with B and ends with ER.", penaltySeconds: 30 },
      3: { order: 3, text: "B-U-T-T-E-R.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-5",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A spice rack cipher reads:\n'GRAILC'\nUnscramble this 6-letter anagram to name the pungent bulb vegetable.",
    answer: "garlic",
    acceptedAnswers: ["garlic"],
    hints: {
      1: { order: 1, text: "A bulbous plant of the allium family used worldwide in savory cooking.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with G and ends with C.", penaltySeconds: 30 },
      3: { order: 3, text: "G-A-R-L-I-C.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-6",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A pantry root label displays the anagram:\n'EGINGR'\nUnscramble this 6-letter word to name the aromatic spicy root.",
    answer: "ginger",
    acceptedAnswers: ["ginger"],
    hints: {
      1: { order: 1, text: "A pungent underground rhizome used in cooking and teas.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts and has another G inside.", penaltySeconds: 30 },
      3: { order: 3, text: "G-I-N-G-E-R.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-7",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A vegetable crate cipher reads:\n'INNOO'\nUnscramble this 5-letter anagram to identify the layered vegetable bulb.",
    answer: "onion",
    acceptedAnswers: ["onion"],
    hints: {
      1: { order: 1, text: "A pungent round vegetable with paper-like skin and concentric layers.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts and ends with O and N.", penaltySeconds: 30 },
      3: { order: 3, text: "O-N-I-O-N.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-8",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A recipe card cipher reads:\n'OMTATO'\nUnscramble this 6-letter word to reveal the red salad fruit.",
    answer: "tomato",
    acceptedAnswers: ["tomato"],
    hints: {
      1: { order: 1, text: "A glossy red, pulpy fruit eaten as a vegetable.", penaltySeconds: 15 },
      2: { order: 2, text: "Begins with T and ends with O.", penaltySeconds: 30 },
      3: { order: 3, text: "T-O-M-A-T-O.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-9",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A citrus shipment manifest reads:\n'ONMEL'\nUnscramble this 5-letter anagram to reveal the yellow sour fruit.",
    answer: "lemon",
    acceptedAnswers: ["lemon"],
    hints: {
      1: { order: 1, text: "A yellow oval citrus fruit with acidic juice.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with L and ends with N.", penaltySeconds: 30 },
      3: { order: 3, text: "L-E-M-O-N.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-10",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "An oil barrel cipher reads:\n'VIELO'\nUnscramble this 5-letter anagram to reveal the Mediterranean stone fruit.",
    answer: "olive",
    acceptedAnswers: ["olive"],
    hints: {
      1: { order: 1, text: "A small oval fruit used to press culinary oil.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with O and ends with E.", penaltySeconds: 30 },
      3: { order: 3, text: "O-L-I-V-E.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-11",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "An herb garden marker reads:\n'ABISL'\nUnscramble this 5-letter anagram to name the aromatic culinary herb.",
    answer: "basil",
    acceptedAnswers: ["basil"],
    hints: {
      1: { order: 1, text: "A fragrant culinary herb of the mint family, key in pesto.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with B and ends with L.", penaltySeconds: 30 },
      3: { order: 3, text: "B-A-S-I-L.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-12",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A dried seasoning container cipher reads:\n'YMTHE'\nUnscramble this 5-letter word to name the small-leaved garden herb.",
    answer: "thyme",
    acceptedAnswers: ["thyme"],
    hints: {
      1: { order: 1, text: "A pungent perennial herb with tiny aromatic leaves.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with T and ends with E.", penaltySeconds: 30 },
      3: { order: 3, text: "T-H-Y-M-E.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-13",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "An acidic dressing bottle reads:\n'NVEIGRA'\nUnscramble this 7-letter anagram to identify the sour condiment liquid.",
    answer: "vinegar",
    acceptedAnswers: ["vinegar"],
    hints: {
      1: { order: 1, text: "A sour liquid consisting mainly of acetic acid and water.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with V and ends with R.", penaltySeconds: 30 },
      3: { order: 3, text: "V-I-N-E-G-A-R.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-14",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A sweet syrup jar label reads:\n'HNYOE'\nUnscramble this 5-letter anagram to name the golden bee nectar.",
    answer: "honey",
    acceptedAnswers: ["honey"],
    hints: {
      1: { order: 1, text: "A sweet, viscous food substance made by honey bees.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with H and ends with Y.", penaltySeconds: 30 },
      3: { order: 3, text: "H-O-N-E-Y.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-15",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A confectionery flavoring tag reads:\n'MTIN'\nUnscramble this 4-letter anagram to name the cooling herb.",
    answer: "mint",
    acceptedAnswers: ["mint"],
    hints: {
      1: { order: 1, text: "An aromatic plant with refreshing, cool-flavored leaves.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with M and ends with T.", penaltySeconds: 30 },
      3: { order: 3, text: "M-I-N-T.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-16",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A bakery leavening packet cipher reads:\n'STAYE'\nUnscramble this 5-letter anagram to name the biological leavening fungus.",
    answer: "yeast",
    acceptedAnswers: ["yeast"],
    hints: {
      1: { order: 1, text: "A microscopic fungus capable of converting sugar into alcohol and CO2.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with Y and ends with T.", penaltySeconds: 30 },
      3: { order: 3, text: "Y-E-A-S-T.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-17",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A grain bin tag reads:\n'LROUF'\nUnscramble this 5-letter anagram to identify the powdery baking grain.",
    answer: "flour",
    acceptedAnswers: ["flour"],
    hints: {
      1: { order: 1, text: "Powder obtained by grinding raw grains, used to make bread.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with F and ends with R.", penaltySeconds: 30 },
      3: { order: 3, text: "F-L-O-U-R.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-18",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A dairy vault inventory code reads:\n'SECEHE'\nUnscramble this 6-letter anagram to identify the coagulated dairy product.",
    answer: "cheese",
    acceptedAnswers: ["cheese"],
    hints: {
      1: { order: 1, text: "A food made from the pressed curds of milk.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with CH and ends with E.", penaltySeconds: 30 },
      3: { order: 3, text: "C-H-E-E-S-E.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-19",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A boiler feedwater manifest reads:\n'WTEAR'\nUnscramble this 5-letter anagram to reveal the primary solvent molecule.",
    answer: "water",
    acceptedAnswers: ["water"],
    hints: {
      1: { order: 1, text: "A transparent liquid compound of hydrogen and oxygen (H2O).", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with W and ends with R.", penaltySeconds: 30 },
      3: { order: 3, text: "W-A-T-E-R.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-20",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "An exotic spice jar reads:\n'MCUNIN'\nUnscramble this 5-letter word (removing redundant letter) or 5-letter spice:\n'MNUCI'\nUnscramble to identify the aromatic ground seed spice.",
    answer: "cumin",
    acceptedAnswers: ["cumin"],
    hints: {
      1: { order: 1, text: "A spice made from the dried seeds of a plant in the parsley family.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with C and ends with N.", penaltySeconds: 30 },
      3: { order: 3, text: "C-U-M-I-N.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-21",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "An aromatic spice bud cipher reads:\n'LVEOC'\nUnscramble this 5-letter anagram to name the dried flower bud spice.",
    answer: "clove",
    acceptedAnswers: ["clove"],
    hints: {
      1: { order: 1, text: "The aromatic flower buds of a tree native to the Maluku Islands.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with C and ends with E.", penaltySeconds: 30 },
      3: { order: 3, text: "C-L-O-V-E.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-22",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A silo grain manifest displays:\n'WHTAE'\nUnscramble this 5-letter anagram to name the staple cereal grass.",
    answer: "wheat",
    acceptedAnswers: ["wheat"],
    hints: {
      1: { order: 1, text: "A cereal grain used to produce modern bread flour.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with W and ends with T.", penaltySeconds: 30 },
      3: { order: 3, text: "W-H-E-A-T.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-5-23",
    levelId: 5,
    difficulty: "MEDIUM",
    type: "cipher",
    category: "Anagram Decryption",
    question: "A maize processing report reads:\n'CRNO'\nUnscramble this 4-letter anagram to reveal the yellow ear grain.",
    answer: "corn",
    acceptedAnswers: ["corn", "maize"],
    hints: {
      1: { order: 1, text: "Also known as maize, a tall grain plant producing yellow kernels.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with C and ends with N.", penaltySeconds: 30 },
      3: { order: 3, text: "C-O-R-N.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
];
