import { QuestionDefinition } from "../questionBank";

export const LEVEL_4_QUESTIONS: QuestionDefinition[] = [
  {
    id: "ch-4",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The acoustic resonance model in the auditorium follows the polynomial:\nP(x) = 3 * x² + 12\nEvaluate the acoustic pressure at frequency node x = 7.",
    answer: "159",
    acceptedAnswers: ["159", "one hundred fifty nine", "one hundred fifty-nine"],
    hints: {
      1: { order: 1, text: "Calculate the square of the frequency node first: 7 * 7.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply 49 by 3, then add the constant 12.", penaltySeconds: 30 },
      3: { order: 3, text: "(3 * 49) + 12 = 147 + 12 = 159.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-2",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The auditorium sound-damping coefficient function is:\nQ(n) = 4 * n² + 5\nEvaluate this coefficient for damping mode n = 6.",
    answer: "149",
    acceptedAnswers: ["149", "one hundred forty nine", "one hundred forty-nine"],
    hints: {
      1: { order: 1, text: "First calculate 6 squared: 6 * 6 = 36.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply 36 by 4: 4 * 36 = 144.", penaltySeconds: 30 },
      3: { order: 3, text: "Add 5: 144 + 5 = 149.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-3",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The stage lighting bus address formula is:\nB(n) = 2 * n² + 25\nEvaluate the bus address for dimmer bank n = 8.",
    answer: "153",
    acceptedAnswers: ["153", "one hundred fifty three", "one hundred fifty-three"],
    hints: {
      1: { order: 1, text: "Square 8: 8 * 8 = 64.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply 64 by 2: 2 * 64 = 128.", penaltySeconds: 30 },
      3: { order: 3, text: "Add 25: 128 + 25 = 153.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-4",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The audio crossover filter curve is modeled by:\nF(x) = 2 * x² + 18\nCalculate the filter gain at x = 6.",
    answer: "90",
    acceptedAnswers: ["90", "ninety"],
    hints: {
      1: { order: 1, text: "Square 6: 6 * 6 = 36.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply by 2: 2 * 36 = 72.", penaltySeconds: 30 },
      3: { order: 3, text: "72 + 18 = 90.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-5",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The reverberation energy index follows:\nS(n) = 3 * n² + 20\nEvaluate for parameter n = 5.",
    answer: "95",
    acceptedAnswers: ["95", "ninety five", "ninety-five"],
    hints: {
      1: { order: 1, text: "5 squared is 25.", penaltySeconds: 15 },
      2: { order: 2, text: "3 * 25 = 75.", penaltySeconds: 30 },
      3: { order: 3, text: "75 + 20 = 95.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-6",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The microphone preamplifier response equation is:\nR(x) = 5 * x² + 11\nEvaluate for input factor x = 4.",
    answer: "91",
    acceptedAnswers: ["91", "ninety one", "ninety-one"],
    hints: {
      1: { order: 1, text: "Square 4: 4 * 4 = 16.", penaltySeconds: 15 },
      2: { order: 2, text: "5 * 16 = 80.", penaltySeconds: 30 },
      3: { order: 3, text: "80 + 11 = 91.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-7",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The speaker array phase shift polynomial is:\nT(n) = 4 * n² + 15\nCalculate the phase value for n = 5.",
    answer: "115",
    acceptedAnswers: ["115", "one hundred fifteen"],
    hints: {
      1: { order: 1, text: "Square 5: 5 * 5 = 25.", penaltySeconds: 15 },
      2: { order: 2, text: "4 * 25 = 100.", penaltySeconds: 30 },
      3: { order: 3, text: "100 + 15 = 115.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-8",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The harmonic distortion profile is expressed by:\nH(x) = x² + 40\nEvaluate for frequency multiplier x = 9.",
    answer: "121",
    acceptedAnswers: ["121", "one hundred twenty one", "one hundred twenty-one"],
    hints: {
      1: { order: 1, text: "9 squared is 81.", penaltySeconds: 15 },
      2: { order: 2, text: "Add 40 to 81.", penaltySeconds: 30 },
      3: { order: 3, text: "81 + 40 = 121.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-9",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The audio amplifier output power follows:\nA(n) = 3 * n² + 10\nEvaluate for drive stage n = 6.",
    answer: "118",
    acceptedAnswers: ["118", "one hundred eighteen"],
    hints: {
      1: { order: 1, text: "Square 6: 6 * 6 = 36.", penaltySeconds: 15 },
      2: { order: 2, text: "3 * 36 = 108.", penaltySeconds: 30 },
      3: { order: 3, text: "108 + 10 = 118.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-10",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The sound reflection coefficient is given by:\nV(x) = 2 * x² + 35\nEvaluate for angle mode x = 7.",
    answer: "133",
    acceptedAnswers: ["133", "one hundred thirty three", "one hundred thirty-three"],
    hints: {
      1: { order: 1, text: "Square 7: 7 * 7 = 49.", penaltySeconds: 15 },
      2: { order: 2, text: "2 * 49 = 98.", penaltySeconds: 30 },
      3: { order: 3, text: "98 + 35 = 133.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-11",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The standing wave node formula is:\nK(n) = 5 * n² + 14\nEvaluate for harmonic index n = 5.",
    answer: "139",
    acceptedAnswers: ["139", "one hundred thirty nine", "one hundred thirty-nine"],
    hints: {
      1: { order: 1, text: "5 * 5 = 25.", penaltySeconds: 15 },
      2: { order: 2, text: "5 * 25 = 125.", penaltySeconds: 30 },
      3: { order: 3, text: "125 + 14 = 139.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-12",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The spatial acoustic diffusion model is:\nM(x) = 4 * x² + 22\nCalculate the output value for parameter x = 6.",
    answer: "166",
    acceptedAnswers: ["166", "one hundred sixty six", "one hundred sixty-six"],
    hints: {
      1: { order: 1, text: "6 squared is 36.", penaltySeconds: 15 },
      2: { order: 2, text: "4 * 36 = 144.", penaltySeconds: 30 },
      3: { order: 3, text: "144 + 22 = 166.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-13",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The digital audio delay tap spacing polynomial is:\nD(n) = 2 * n² + 50\nEvaluate for buffer index n = 8.",
    answer: "178",
    acceptedAnswers: ["178", "one hundred seventy eight", "one hundred seventy-eight"],
    hints: {
      1: { order: 1, text: "8 * 8 = 64.", penaltySeconds: 15 },
      2: { order: 2, text: "2 * 64 = 128.", penaltySeconds: 30 },
      3: { order: 3, text: "128 + 50 = 178.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-14",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The equalizer envelope curve polynomial is:\nE(x) = 3 * x² + 15\nCalculate the amplitude response at band x = 7.",
    answer: "162",
    acceptedAnswers: ["162", "one hundred sixty two", "one hundred sixty-two"],
    hints: {
      1: { order: 1, text: "7 squared is 49.", penaltySeconds: 15 },
      2: { order: 2, text: "3 * 49 = 147.", penaltySeconds: 30 },
      3: { order: 3, text: "147 + 15 = 162.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-15",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The acoustic absorption index formula is:\nW(n) = n² + 65\nEvaluate for absorption mode n = 8.",
    answer: "129",
    acceptedAnswers: ["129", "one hundred twenty nine", "one hundred twenty-nine"],
    hints: {
      1: { order: 1, text: "8 squared is 64.", penaltySeconds: 15 },
      2: { order: 2, text: "Add 65 to 64.", penaltySeconds: 30 },
      3: { order: 3, text: "64 + 65 = 129.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-16",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The loudspeaker cone excursion polynomial is:\nC(x) = 2 * x² + 11\nEvaluate for displacement parameter x = 9.",
    answer: "173",
    acceptedAnswers: ["173", "one hundred seventy three", "one hundred seventy-three"],
    hints: {
      1: { order: 1, text: "9 squared is 81.", penaltySeconds: 15 },
      2: { order: 2, text: "2 * 81 = 162.", penaltySeconds: 30 },
      3: { order: 3, text: "162 + 11 = 173.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-17",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The sound level attenuation model follows:\nL(n) = 6 * n² + 7\nCalculate for distance rank n = 4.",
    answer: "103",
    acceptedAnswers: ["103", "one hundred three"],
    hints: {
      1: { order: 1, text: "4 * 4 = 16.", penaltySeconds: 15 },
      2: { order: 2, text: "6 * 16 = 96.", penaltySeconds: 30 },
      3: { order: 3, text: "96 + 7 = 103.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-18",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The auditorium sound reinforcement polynomial is:\nG(x) = 3 * x² + 45\nEvaluate for amplification zone x = 5.",
    answer: "120",
    acceptedAnswers: ["120", "one hundred twenty"],
    hints: {
      1: { order: 1, text: "5 squared is 25.", penaltySeconds: 15 },
      2: { order: 2, text: "3 * 25 = 75.", penaltySeconds: 30 },
      3: { order: 3, text: "75 + 45 = 120.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-19",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The soundboard impedance curve polynomial is:\nY(n) = 4 * n² + 37\nEvaluate for vibration mode n = 5.",
    answer: "137",
    acceptedAnswers: ["137", "one hundred thirty seven", "one hundred thirty-seven"],
    hints: {
      1: { order: 1, text: "5 * 5 = 25.", penaltySeconds: 15 },
      2: { order: 2, text: "4 * 25 = 100.", penaltySeconds: 30 },
      3: { order: 3, text: "100 + 37 = 137.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-20",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The wave dispersion polynomial is given by:\nZ(x) = 2 * x² + 17\nCalculate for wave vector x = 8.",
    answer: "145",
    acceptedAnswers: ["145", "one hundred forty five", "one hundred forty-five"],
    hints: {
      1: { order: 1, text: "8 squared is 64.", penaltySeconds: 15 },
      2: { order: 2, text: "2 * 64 = 128.", penaltySeconds: 30 },
      3: { order: 3, text: "128 + 17 = 145.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-21",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The acoustic feedback suppression threshold follows:\nU(n) = 5 * n² + 19\nEvaluate for parameter n = 4.",
    answer: "99",
    acceptedAnswers: ["99", "ninety nine", "ninety-nine"],
    hints: {
      1: { order: 1, text: "4 * 4 = 16.", penaltySeconds: 15 },
      2: { order: 2, text: "5 * 16 = 80.", penaltySeconds: 30 },
      3: { order: 3, text: "80 + 19 = 99.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-22",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The hall volume reverberation constant follows:\nN(x) = 3 * x² + 8\nCalculate the constant for dimension factor x = 8.",
    answer: "200",
    acceptedAnswers: ["200", "two hundred"],
    hints: {
      1: { order: 1, text: "8 * 8 = 64.", penaltySeconds: 15 },
      2: { order: 2, text: "3 * 64 = 192.", penaltySeconds: 30 },
      3: { order: 3, text: "192 + 8 = 200.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-4-23",
    levelId: 4,
    difficulty: "MEDIUM",
    type: "math",
    category: "Acoustics Polynomial",
    question: "The acoustic baffle spacing equation is:\nJ(n) = 2 * n² + 42\nEvaluate for baffle index n = 7.",
    answer: "140",
    acceptedAnswers: ["140", "one hundred forty"],
    hints: {
      1: { order: 1, text: "7 * 7 = 49.", penaltySeconds: 15 },
      2: { order: 2, text: "2 * 49 = 98.", penaltySeconds: 30 },
      3: { order: 3, text: "98 + 42 = 140.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
];
