import { QuestionDefinition } from "../questionBank";

export const LEVEL_10_QUESTIONS: QuestionDefinition[] = [
  {
    id: "ch-10",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "System Hardware",
    question: "The primary input peripheral used for entering text and commands containing alphanumeric keys is the: ______.",
    answer: "keyboard",
    acceptedAnswers: ["keyboard"],
    hints: {
      1: { order: 1, text: "It contains keys like Enter, Space, and Escape.", penaltySeconds: 15 },
      2: { order: 2, text: "It begins with K and ends with D.", penaltySeconds: 30 },
      3: { order: 3, text: "K-E-Y-B-O-A-R-D.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-2",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "System Hardware",
    question: "The primary handheld pointing peripheral that detects two-dimensional motion relative to a surface is the: ______.",
    answer: "mouse",
    acceptedAnswers: ["mouse"],
    hints: {
      1: { order: 1, text: "It typically features left and right click buttons and a scroll wheel.", penaltySeconds: 15 },
      2: { order: 2, text: "It begins with M and shares its name with a small rodent.", penaltySeconds: 30 },
      3: { order: 3, text: "M-O-U-S-E.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-3",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "System Hardware",
    question: "The primary computational processor of a computer that executes machine instructions is known by the acronym: ______.",
    answer: "cpu",
    acceptedAnswers: ["cpu", "central processing unit"],
    hints: {
      1: { order: 1, text: "Three-letter acronym standing for Central Processing Unit.", penaltySeconds: 15 },
      2: { order: 2, text: "It is often called the 'brain' of the computer.", penaltySeconds: 30 },
      3: { order: 3, text: "C-P-U.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-4",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "CPU Architecture",
    question: "The dedicated combinational circuit within a CPU that performs arithmetic integer operations and bitwise logic is known as the: ______ (acronym).",
    answer: "alu",
    acceptedAnswers: ["alu", "arithmetic logic unit"],
    hints: {
      1: { order: 1, text: "Stands for Arithmetic Logic Unit.", penaltySeconds: 15 },
      2: { order: 2, text: "Three-letter acronym starting with A.", penaltySeconds: 30 },
      3: { order: 3, text: "A-L-U.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-5",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "System Firmware",
    question: "The firmware program built into motherboard non-volatile memory that initializes system hardware components during the boot process is the: ______ (acronym).",
    answer: "bios",
    acceptedAnswers: ["bios", "basic input output system"],
    hints: {
      1: { order: 1, text: "Stands for Basic Input/Output System.", penaltySeconds: 15 },
      2: { order: 2, text: "Four-letter acronym starting with B.", penaltySeconds: 30 },
      3: { order: 3, text: "B-I-O-S.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-6",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "Memory Architecture",
    question: "The primary high-speed volatile random-access working memory directly read and written by the CPU during program execution is: ______ (acronym).",
    answer: "ram",
    acceptedAnswers: ["ram", "random access memory"],
    hints: {
      1: { order: 1, text: "Stands for Random Access Memory.", penaltySeconds: 15 },
      2: { order: 2, text: "Three-letter acronym starting with R.", penaltySeconds: 30 },
      3: { order: 3, text: "R-A-M.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-7",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "Memory Architecture",
    question: "Non-volatile memory that contains permanent binary code and cannot be modified under normal system operations is known as: ______ (acronym).",
    answer: "rom",
    acceptedAnswers: ["rom", "read only memory"],
    hints: {
      1: { order: 1, text: "Stands for Read-Only Memory.", penaltySeconds: 15 },
      2: { order: 2, text: "Three-letter acronym starting with R.", penaltySeconds: 30 },
      3: { order: 3, text: "R-O-M.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-8",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "System Hardware",
    question: "The specialized massively-parallel coprocessor designed specifically to accelerate the rendering of 2D/3D graphics and tensor operations is the: ______ (acronym).",
    answer: "gpu",
    acceptedAnswers: ["gpu", "graphics processing unit"],
    hints: {
      1: { order: 1, text: "Stands for Graphics Processing Unit.", penaltySeconds: 15 },
      2: { order: 2, text: "Three-letter acronym starting with G.", penaltySeconds: 30 },
      3: { order: 3, text: "G-P-U.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-9",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "Memory Architecture",
    question: "The hardware unit that handles the translation of virtual memory addresses into physical RAM addresses using page tables is the: ______ (acronym).",
    answer: "mmu",
    acceptedAnswers: ["mmu", "memory management unit"],
    hints: {
      1: { order: 1, text: "Stands for Memory Management Unit.", penaltySeconds: 15 },
      2: { order: 2, text: "Three-letter acronym starting with M.", penaltySeconds: 30 },
      3: { order: 3, text: "M-M-U.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-10",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "Bus Architecture",
    question: "The system feature that allows high-throughput hardware subsystems to read and write directly to main system memory without loading the CPU is: ______ (acronym).",
    answer: "dma",
    acceptedAnswers: ["dma", "direct memory access"],
    hints: {
      1: { order: 1, text: "Stands for Direct Memory Access.", penaltySeconds: 15 },
      2: { order: 2, text: "Three-letter acronym starting with D.", penaltySeconds: 30 },
      3: { order: 3, text: "D-M-A.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-11",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "Data Units",
    question: "The fundamental unit of addressable digital data storage in modern computer systems consisting of exactly 8 bits is the: ______.",
    answer: "byte",
    acceptedAnswers: ["byte"],
    hints: {
      1: { order: 1, text: "A sequence of eight binary digits.", penaltySeconds: 15 },
      2: { order: 2, text: "Four-letter word starting with B.", penaltySeconds: 30 },
      3: { order: 3, text: "B-Y-T-E.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-12",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "System Firmware",
    question: "The modern standardized specification replacing legacy BIOS that supports secure boot, larger drives, and faster initialization is: ______ (acronym).",
    answer: "uefi",
    acceptedAnswers: ["uefi", "unified extensible firmware interface"],
    hints: {
      1: { order: 1, text: "Unified Extensible Firmware Interface.", penaltySeconds: 15 },
      2: { order: 2, text: "Four-letter acronym starting with U.", penaltySeconds: 30 },
      3: { order: 3, text: "U-E-F-I.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-13",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "Storage Architecture",
    question: "The semiconductor-based persistent storage device with no moving mechanical parts that has superseded magnetic hard disk drives is the: ______ (acronym).",
    answer: "ssd",
    acceptedAnswers: ["ssd", "solid state drive"],
    hints: {
      1: { order: 1, text: "Stands for Solid State Drive.", penaltySeconds: 15 },
      2: { order: 2, text: "Three-letter acronym starting with S.", penaltySeconds: 30 },
      3: { order: 3, text: "S-S-D.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-14",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "CPU Architecture",
    question: "The fastest, smallest memory storage cells located immediately inside the processor execution core are called: ______.",
    answer: "registers",
    acceptedAnswers: ["registers", "register"],
    hints: {
      1: { order: 1, text: "Includes program counter, accumulator, and general-purpose storage.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with R and ends with S.", penaltySeconds: 30 },
      3: { order: 3, text: "R-E-G-I-S-T-E-R-S.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-15",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "System Hardware",
    question: "The main printed circuit board (PCB) that houses the CPU socket, RAM slots, and interconnect buses is the: ______.",
    answer: "motherboard",
    acceptedAnswers: ["motherboard", "mainboard"],
    hints: {
      1: { order: 1, text: "The primary backbone circuit board connecting all internal peripherals.", penaltySeconds: 15 },
      2: { order: 2, text: "Contains the word 'mother'.", penaltySeconds: 30 },
      3: { order: 3, text: "M-O-T-H-E-R-B-O-A-R-D.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-16",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "System Architecture",
    question: "An asynchronous hardware signal sent to the processor from an external device requesting immediate CPU service is an: ______ (acronym).",
    answer: "irq",
    acceptedAnswers: ["irq", "interrupt request"],
    hints: {
      1: { order: 1, text: "Stands for Interrupt Request.", penaltySeconds: 15 },
      2: { order: 2, text: "Three-letter acronym starting with I.", penaltySeconds: 30 },
      3: { order: 3, text: "I-R-Q.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-17",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "Storage Architecture",
    question: "The high-speed host controller interface and storage protocol designed specifically to connect flash SSDs over PCIe lanes is: ______ (acronym).",
    answer: "nvme",
    acceptedAnswers: ["nvme", "non volatile memory express"],
    hints: {
      1: { order: 1, text: "Non-Volatile Memory Express.", penaltySeconds: 15 },
      2: { order: 2, text: "Four-letter acronym starting with N.", penaltySeconds: 30 },
      3: { order: 3, text: "N-V-M-E.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-18",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "Hardware Security",
    question: "The dedicated cryptoprocessor chip on modern motherboards that provides hardware-based security and root-of-trust encryption keys is the: ______ (acronym).",
    answer: "tpm",
    acceptedAnswers: ["tpm", "trusted platform module"],
    hints: {
      1: { order: 1, text: "Stands for Trusted Platform Module.", penaltySeconds: 15 },
      2: { order: 2, text: "Three-letter acronym starting with T.", penaltySeconds: 30 },
      3: { order: 3, text: "T-P-M.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-19",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "CPU Architecture",
    question: "How many bits constitute a standard quadword or standard register memory word on modern x86_64 processor architectures?",
    answer: "64",
    acceptedAnswers: ["64", "64 bits"],
    hints: {
      1: { order: 1, text: "64-bit computation width.", penaltySeconds: 15 },
      2: { order: 2, text: "Equal to 8 bytes.", penaltySeconds: 30 },
      3: { order: 3, text: "8 * 8 = 64.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-20",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "System Hardware",
    question: "The internal chassis component that converts mains alternating current (AC) into regulated low-voltage direct current (DC) for components is the: ______ (acronym).",
    answer: "psu",
    acceptedAnswers: ["psu", "power supply unit", "power supply"],
    hints: {
      1: { order: 1, text: "Stands for Power Supply Unit.", penaltySeconds: 15 },
      2: { order: 2, text: "Three-letter acronym starting with P.", penaltySeconds: 30 },
      3: { order: 3, text: "P-S-U.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-21",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "CPU Architecture",
    question: "The register in the CPU control unit that holds the memory address of the next instruction to be fetched and executed is the: ______ (acronym).",
    answer: "pc",
    acceptedAnswers: ["pc", "program counter"],
    hints: {
      1: { order: 1, text: "Stands for Program Counter.", penaltySeconds: 15 },
      2: { order: 2, text: "Two-letter acronym starting with P.", penaltySeconds: 30 },
      3: { order: 3, text: "P-C.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-22",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "Memory Architecture",
    question: "The fastest level of cache memory integrated directly on the processor die closest to execution units is: ______ (acronym).",
    answer: "l1",
    acceptedAnswers: ["l1", "level 1", "level 1 cache"],
    hints: {
      1: { order: 1, text: "Level 1 cache.", penaltySeconds: 15 },
      2: { order: 2, text: "Letter L followed by the numeral 1.", penaltySeconds: 30 },
      3: { order: 3, text: "L1.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-10-23",
    levelId: 10,
    difficulty: "EXPERT",
    type: "hardware",
    category: "System Architecture",
    question: "The piezoelectric component on the motherboard that generates constant electrical oscillations to synchronize CPU clock cycles is the quartz: ______.",
    answer: "crystal",
    acceptedAnswers: ["crystal", "oscillator"],
    hints: {
      1: { order: 1, text: "A quartz mineral that vibrates at a precise frequency when voltage is applied.", penaltySeconds: 15 },
      2: { order: 2, text: "Starts with C and ends with L.", penaltySeconds: 30 },
      3: { order: 3, text: "C-R-Y-S-T-A-L.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
];
