import { QuestionDefinition } from "../questionBank";

export const LEVEL_7_QUESTIONS: QuestionDefinition[] = [
  {
    id: "ch-7",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Signal Processing",
    question: "The digital oscilloscope measures an analog test point with resistance R = 15 Ω carrying a current I = 6 A.\nCalculate the voltage drop V across the test point in volts (V = I * R).",
    answer: "90",
    acceptedAnswers: ["90", "90v", "90 volts", "ninety"],
    hints: {
      1: { order: 1, text: "Ohm's Law states Voltage = Current * Resistance.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply 6 amperes by 15 ohms.", penaltySeconds: 30 },
      3: { order: 3, text: "6 * 15 = 90.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-2",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Signal Processing",
    question: "A periodic waveform on channel 1 has period T = 12.5 milliseconds (0.0125 s).\nCalculate the frequency f in Hertz (f = 1 / T).",
    answer: "80",
    acceptedAnswers: ["80", "80hz", "80 hertz", "eighty"],
    hints: {
      1: { order: 1, text: "Frequency is the reciprocal of the period in seconds: 1 / 0.0125.", penaltySeconds: 15 },
      2: { order: 2, text: "1000 ms / 12.5 ms = 80.", penaltySeconds: 30 },
      3: { order: 3, text: "f = 80 Hz.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-3",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "RC Circuits",
    question: "An RC filter circuit contains resistor R = 25 kΩ (25,000 Ω) and capacitor C = 4 µF (0.000004 F).\nCalculate the circuit time constant τ in milliseconds (τ = R * C).",
    answer: "100",
    acceptedAnswers: ["100", "100ms", "100 milliseconds", "one hundred"],
    hints: {
      1: { order: 1, text: "Time constant tau = R * C in seconds.", penaltySeconds: 15 },
      2: { order: 2, text: "25,000 * 0.000004 = 0.10 seconds.", penaltySeconds: 30 },
      3: { order: 3, text: "0.10 s = 100 milliseconds.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-4",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "A power rail resistor of R = 24 Ω carries a current of I = 5 A.\nCalculate the voltage drop across it in volts.",
    answer: "120",
    acceptedAnswers: ["120", "120v", "120 volts", "one hundred twenty"],
    hints: {
      1: { order: 1, text: "Use V = I * R.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply 5 by 24.", penaltySeconds: 30 },
      3: { order: 3, text: "5 * 24 = 120.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-5",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "A high-precision current shunt has resistance R = 18 Ω carrying current I = 4 A.\nDetermine the voltage drop in volts.",
    answer: "72",
    acceptedAnswers: ["72", "72v", "72 volts", "seventy two", "seventy-two"],
    hints: {
      1: { order: 1, text: "V = I * R.", penaltySeconds: 15 },
      2: { order: 2, text: "18 * 4.", penaltySeconds: 30 },
      3: { order: 3, text: "18 * 4 = 72.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-6",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Signal Processing",
    question: "A reference clock signal has a cycle period T = 20 milliseconds (0.02 s).\nCalculate its frequency in Hertz.",
    answer: "50",
    acceptedAnswers: ["50", "50hz", "50 hertz", "fifty"],
    hints: {
      1: { order: 1, text: "f = 1 / T.", penaltySeconds: 15 },
      2: { order: 2, text: "1 / 0.02 = 100 / 2.", penaltySeconds: 30 },
      3: { order: 3, text: "f = 50 Hz.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-7",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Signal Processing",
    question: "A pulse-width modulator square wave has period T = 10 milliseconds (0.01 s).\nFind its operating frequency in Hertz.",
    answer: "100",
    acceptedAnswers: ["100", "100hz", "100 hertz", "one hundred"],
    hints: {
      1: { order: 1, text: "Frequency is 1 / T in seconds.", penaltySeconds: 15 },
      2: { order: 2, text: "1 / 0.01.", penaltySeconds: 30 },
      3: { order: 3, text: "1 / 0.01 = 100 Hz.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-8",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Signal Processing",
    question: "An ultrasonic sensor transducer resonates with period T = 4 milliseconds (0.004 s).\nWhat is its frequency in Hertz?",
    answer: "250",
    acceptedAnswers: ["250", "250hz", "250 hertz", "two hundred fifty"],
    hints: {
      1: { order: 1, text: "f = 1000 / T (in ms).", penaltySeconds: 15 },
      2: { order: 2, text: "1000 / 4.", penaltySeconds: 30 },
      3: { order: 3, text: "1000 / 4 = 250 Hz.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-9",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "Two resistors R1 = 60 Ω and R2 = 40 Ω are connected in series.\nCalculate the total equivalent resistance in ohms.",
    answer: "100",
    acceptedAnswers: ["100", "100 ohms", "100 ohm", "one hundred"],
    hints: {
      1: { order: 1, text: "Series resistance is the direct sum: R_total = R1 + R2.", penaltySeconds: 15 },
      2: { order: 2, text: "60 + 40.", penaltySeconds: 30 },
      3: { order: 3, text: "60 + 40 = 100.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-10",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "Two resistors R1 = 60 Ω and R2 = 30 Ω are connected in parallel.\nCalculate their equivalent resistance in ohms.",
    answer: "20",
    acceptedAnswers: ["20", "20 ohms", "20 ohm", "twenty"],
    hints: {
      1: { order: 1, text: "Parallel formula: (R1 * R2) / (R1 + R2).", penaltySeconds: 15 },
      2: { order: 2, text: "(60 * 30) / (60 + 30) = 1800 / 90.", penaltySeconds: 30 },
      3: { order: 3, text: "1800 / 90 = 20.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-11",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "Two identical 100 Ω resistors are placed in parallel across a circuit branch.\nWhat is their combined equivalent resistance in ohms?",
    answer: "50",
    acceptedAnswers: ["50", "50 ohms", "50 ohm", "fifty"],
    hints: {
      1: { order: 1, text: "Two identical parallel resistors have an equivalent resistance equal to half of one resistor.", penaltySeconds: 15 },
      2: { order: 2, text: "100 / 2.", penaltySeconds: 30 },
      3: { order: 3, text: "100 / 2 = 50.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-12",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "RC Circuits",
    question: "An integrator circuit has resistance R = 40 kΩ (40,000 Ω) and capacitance C = 3 µF (0.000003 F).\nCalculate the time constant τ in milliseconds.",
    answer: "120",
    acceptedAnswers: ["120", "120ms", "120 milliseconds", "one hundred twenty"],
    hints: {
      1: { order: 1, text: "tau = R * C.", penaltySeconds: 15 },
      2: { order: 2, text: "40,000 * 0.000003 = 0.12 seconds.", penaltySeconds: 30 },
      3: { order: 3, text: "0.12 s = 120 ms.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-13",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "A DC power supply delivers V = 24 V to a load drawing current I = 5 A.\nCalculate the power consumed in watts (P = V * I).",
    answer: "120",
    acceptedAnswers: ["120", "120w", "120 watts", "one hundred twenty"],
    hints: {
      1: { order: 1, text: "Power = Voltage * Current.", penaltySeconds: 15 },
      2: { order: 2, text: "Multiply 24 by 5.", penaltySeconds: 30 },
      3: { order: 3, text: "24 * 5 = 120 W.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-14",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "A high-power heating element dissipates P = 200 W when connected to a V = 50 V source.\nCalculate the current drawn in amperes.",
    answer: "4",
    acceptedAnswers: ["4", "4a", "4 amps", "4 amperes", "four"],
    hints: {
      1: { order: 1, text: "Current I = Power / Voltage.", penaltySeconds: 15 },
      2: { order: 2, text: "200 / 50.", penaltySeconds: 30 },
      3: { order: 3, text: "200 / 50 = 4 A.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-15",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "A voltage of V = 60 V is applied across a load resistor of R = 12 Ω.\nCalculate the resulting current in amperes.",
    answer: "5",
    acceptedAnswers: ["5", "5a", "5 amps", "5 amperes", "five"],
    hints: {
      1: { order: 1, text: "I = V / R.", penaltySeconds: 15 },
      2: { order: 2, text: "60 / 12.", penaltySeconds: 30 },
      3: { order: 3, text: "60 / 12 = 5.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-16",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "A circuit branch has resistance R = 22 Ω with current I = 3 A flowing through it.\nCalculate the voltage drop in volts.",
    answer: "66",
    acceptedAnswers: ["66", "66v", "66 volts", "sixty six", "sixty-six"],
    hints: {
      1: { order: 1, text: "V = I * R.", penaltySeconds: 15 },
      2: { order: 2, text: "22 * 3.", penaltySeconds: 30 },
      3: { order: 3, text: "22 * 3 = 66.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-17",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Signal Processing",
    question: "A crystal oscillator clock signal period is measured at T = 5 milliseconds (0.005 s).\nWhat is its frequency in Hertz?",
    answer: "200",
    acceptedAnswers: ["200", "200hz", "200 hertz", "two hundred"],
    hints: {
      1: { order: 1, text: "f = 1 / 0.005.", penaltySeconds: 15 },
      2: { order: 2, text: "1000 / 5.", penaltySeconds: 30 },
      3: { order: 3, text: "1000 / 5 = 200 Hz.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-18",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "Three resistors R1 = 40 Ω, R2 = 60 Ω, and R3 = 50 Ω are wired in series.\nCalculate the total resistance in ohms.",
    answer: "150",
    acceptedAnswers: ["150", "150 ohms", "one hundred fifty"],
    hints: {
      1: { order: 1, text: "Sum all three series resistors.", penaltySeconds: 15 },
      2: { order: 2, text: "40 + 60 + 50.", penaltySeconds: 30 },
      3: { order: 3, text: "40 + 60 + 50 = 150.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-19",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "Two parallel resistors R1 = 120 Ω and R2 = 60 Ω are connected to a node.\nWhat is their equivalent resistance in ohms?",
    answer: "40",
    acceptedAnswers: ["40", "40 ohms", "forty"],
    hints: {
      1: { order: 1, text: "(R1 * R2) / (R1 + R2).", penaltySeconds: 15 },
      2: { order: 2, text: "(120 * 60) / (120 + 60) = 7200 / 180.", penaltySeconds: 30 },
      3: { order: 3, text: "7200 / 180 = 40.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-20",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "A power converter delivers V = 110 V at current I = 2 A.\nWhat is the power output in watts?",
    answer: "220",
    acceptedAnswers: ["220", "220w", "220 watts", "two hundred twenty"],
    hints: {
      1: { order: 1, text: "P = V * I.", penaltySeconds: 15 },
      2: { order: 2, text: "110 * 2.", penaltySeconds: 30 },
      3: { order: 3, text: "110 * 2 = 220 W.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-21",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Signal Processing",
    question: "A low-frequency synthesizer waveform cycle has period T = 8 milliseconds (0.008 s).\nCalculate the frequency in Hertz.",
    answer: "125",
    acceptedAnswers: ["125", "125hz", "125 hertz", "one hundred twenty five"],
    hints: {
      1: { order: 1, text: "f = 1000 / 8.", penaltySeconds: 15 },
      2: { order: 2, text: "1000 / 8 = 125.", penaltySeconds: 30 },
      3: { order: 3, text: "f = 125 Hz.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-22",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "RC Circuits",
    question: "A timing delay RC circuit uses resistor R = 10 kΩ (10,000 Ω) and capacitor C = 5 µF (0.000005 F).\nCalculate the time constant τ in milliseconds.",
    answer: "50",
    acceptedAnswers: ["50", "50ms", "50 milliseconds", "fifty"],
    hints: {
      1: { order: 1, text: "tau = R * C.", penaltySeconds: 15 },
      2: { order: 2, text: "10,000 * 0.000005 = 0.05 seconds.", penaltySeconds: 30 },
      3: { order: 3, text: "0.05 s = 50 ms.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-7-23",
    levelId: 7,
    difficulty: "HARD",
    type: "circuits",
    category: "Circuit Engineering",
    question: "A circuit provides V = 75 V across an internal resistance of R = 25 Ω.\nDetermine the current in amperes.",
    answer: "3",
    acceptedAnswers: ["3", "3a", "3 amps", "3 amperes", "three"],
    hints: {
      1: { order: 1, text: "I = V / R.", penaltySeconds: 15 },
      2: { order: 2, text: "75 / 25.", penaltySeconds: 30 },
      3: { order: 3, text: "75 / 25 = 3 A.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
];
