import { QuestionDefinition } from "../questionBank";

export const LEVEL_9_QUESTIONS: QuestionDefinition[] = [
  {
    id: "ch-9",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Security",
    question: "The campus perimeter firewall blocks all non-essential ingress ports.\nEnter the standard TCP port number for secure HTTPS web administration.",
    answer: "443",
    acceptedAnswers: ["443", "port 443"],
    hints: {
      1: { order: 1, text: "Standard unencrypted HTTP runs on port 80.", penaltySeconds: 15 },
      2: { order: 2, text: "HTTPS uses a three-digit port beginning with 4.", penaltySeconds: 30 },
      3: { order: 3, text: "The standard port is 443.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-2",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Protocols",
    question: "The encrypted terminal server requires remote shell administration.\nEnter the standard default TCP port number for the Secure Shell (SSH) protocol.",
    answer: "22",
    acceptedAnswers: ["22", "port 22"],
    hints: {
      1: { order: 1, text: "It is one port below telnet (port 23).", penaltySeconds: 15 },
      2: { order: 2, text: "It is a double-digit number where both digits are the same.", penaltySeconds: 30 },
      3: { order: 3, text: "SSH default port is 22.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-3",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "IPv4 Subnetting",
    question: "A network router is configured with subnet 192.168.1.0/24.\nEnter the last usable host IP octet in this subnet (before the broadcast address).",
    answer: "254",
    acceptedAnswers: ["254", ".254"],
    hints: {
      1: { order: 1, text: "In a /24 subnet, the total address space is 256 addresses (0 to 255).", penaltySeconds: 15 },
      2: { order: 2, text: "Address 255 is reserved for broadcast.", penaltySeconds: 30 },
      3: { order: 3, text: "The last usable host octet is 255 - 1 = 254.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-4",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Protocols",
    question: "The campus DNS server resolves hostname queries.\nEnter the standard default port number used for DNS queries (UDP/TCP).",
    answer: "53",
    acceptedAnswers: ["53", "port 53"],
    hints: {
      1: { order: 1, text: "Domain Name System standard port.", penaltySeconds: 15 },
      2: { order: 2, text: "Two-digit number in the fifties.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 53.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-5",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Protocols",
    question: "An unencrypted web server listens on the standard HTTP port.\nEnter this standard port number.",
    answer: "80",
    acceptedAnswers: ["80", "port 80"],
    hints: {
      1: { order: 1, text: "Standard world wide web HTTP port.", penaltySeconds: 15 },
      2: { order: 2, text: "A multiple of 10 under 100.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 80.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-6",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Protocols",
    question: "Legacy network equipment utilizes the unencrypted Telnet protocol.\nWhat is the default TCP port number for Telnet?",
    answer: "23",
    acceptedAnswers: ["23", "port 23"],
    hints: {
      1: { order: 1, text: "Directly adjacent to SSH (port 22).", penaltySeconds: 15 },
      2: { order: 2, text: "22 + 1.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 23.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-7",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Protocols",
    question: "The campus mail relay transmits outgoing messages via SMTP.\nEnter the legacy standard TCP port for SMTP.",
    answer: "25",
    acceptedAnswers: ["25", "port 25"],
    hints: {
      1: { order: 1, text: "Simple Mail Transfer Protocol standard server port.", penaltySeconds: 15 },
      2: { order: 2, text: "Square of 5.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 25.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-8",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Protocols",
    question: "Network time synchronization between servers uses NTP.\nWhat standard UDP port does NTP listen on?",
    answer: "123",
    acceptedAnswers: ["123", "port 123"],
    hints: {
      1: { order: 1, text: "Consecutive ascending digits.", penaltySeconds: 15 },
      2: { order: 2, text: "Three digits: 1, 2, ...", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 123.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-9",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Protocols",
    question: "The network monitoring suite queries switch metrics using SNMP.\nWhat is the default UDP port for SNMP agent queries?",
    answer: "161",
    acceptedAnswers: ["161", "port 161"],
    hints: {
      1: { order: 1, text: "Simple Network Management Protocol query port.", penaltySeconds: 15 },
      2: { order: 2, text: "Three-digit port in the one hundreds.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 161.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-10",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Protocols",
    question: "Remote administration of Windows workstations uses RDP.\nWhat is the default TCP port for Microsoft Remote Desktop Protocol?",
    answer: "3389",
    acceptedAnswers: ["3389", "port 3389"],
    hints: {
      1: { order: 1, text: "Four-digit port starting with 33.", penaltySeconds: 15 },
      2: { order: 2, text: "3380 + 9.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 3389.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-11",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Database Networking",
    question: "The web database cluster communicates with the MySQL server.\nWhat is the default TCP port for MySQL database connections?",
    answer: "3306",
    acceptedAnswers: ["3306", "port 3306"],
    hints: {
      1: { order: 1, text: "Four-digit port beginning with 33.", penaltySeconds: 15 },
      2: { order: 2, text: "Ends in 06.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 3306.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-12",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Database Networking",
    question: "The Core Quest Finder backend connects to PostgreSQL.\nWhat is the default TCP port for PostgreSQL database connections?",
    answer: "5432",
    acceptedAnswers: ["5432", "port 5432"],
    hints: {
      1: { order: 1, text: "Four consecutive descending digits starting from 5.", penaltySeconds: 15 },
      2: { order: 2, text: "5, 4, 3, 2.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 5432.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-13",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Protocols",
    question: "How many total bits comprise a standard IPv4 address?",
    answer: "32",
    acceptedAnswers: ["32", "32 bits"],
    hints: {
      1: { order: 1, text: "IPv4 has 4 octets.", penaltySeconds: 15 },
      2: { order: 2, text: "Each octet has 8 bits: 4 * 8.", penaltySeconds: 30 },
      3: { order: 3, text: "4 * 8 = 32 bits.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-14",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Protocols",
    question: "How many total bits comprise an IPv6 address?",
    answer: "128",
    acceptedAnswers: ["128", "128 bits"],
    hints: {
      1: { order: 1, text: "IPv6 consists of 8 groups of 16 bits.", penaltySeconds: 15 },
      2: { order: 2, text: "8 * 16 = 128.", penaltySeconds: 30 },
      3: { order: 3, text: "Total length is 128 bits.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-15",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Cryptographic Protocols",
    question: "What is the fixed output digest length of the SHA-256 cryptographic hash function in bytes?",
    answer: "32",
    acceptedAnswers: ["32", "32 bytes"],
    hints: {
      1: { order: 1, text: "SHA-256 produces 256 bits.", penaltySeconds: 15 },
      2: { order: 2, text: "Divide 256 bits by 8 bits per byte.", penaltySeconds: 30 },
      3: { order: 3, text: "256 / 8 = 32 bytes.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-16",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Cryptographic Protocols",
    question: "What is the output digest length of the MD5 hash function in bytes?",
    answer: "16",
    acceptedAnswers: ["16", "16 bytes"],
    hints: {
      1: { order: 1, text: "MD5 produces 128 bits.", penaltySeconds: 15 },
      2: { order: 2, text: "Divide 128 by 8.", penaltySeconds: 30 },
      3: { order: 3, text: "128 / 8 = 16 bytes.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-17",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "IPv4 Subnetting",
    question: "An administrative subnet is carved with prefix length /28.\nHow many total IP addresses are available in this subnet block?",
    answer: "16",
    acceptedAnswers: ["16", "16 addresses"],
    hints: {
      1: { order: 1, text: "Host bits = 32 - 28 = 4 bits.", penaltySeconds: 15 },
      2: { order: 2, text: "Calculate 2^4.", penaltySeconds: 30 },
      3: { order: 3, text: "2^4 = 16.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-18",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "IPv4 Subnetting",
    question: "In a /28 subnet (16 total addresses), how many usable host IP addresses can be assigned to devices?",
    answer: "14",
    acceptedAnswers: ["14", "14 hosts"],
    hints: {
      1: { order: 1, text: "Subtract network and broadcast addresses: 2^(32-prefix) - 2.", penaltySeconds: 15 },
      2: { order: 2, text: "16 - 2.", penaltySeconds: 30 },
      3: { order: 3, text: "16 - 2 = 14 usable hosts.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-19",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "IPv4 Subnetting",
    question: "How many total IP addresses exist in a /26 CIDR subnet block?",
    answer: "64",
    acceptedAnswers: ["64", "64 addresses"],
    hints: {
      1: { order: 1, text: "Host bits = 32 - 26 = 6 bits.", penaltySeconds: 15 },
      2: { order: 2, text: "Calculate 2^6.", penaltySeconds: 30 },
      3: { order: 3, text: "2^6 = 64.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-20",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Protocols",
    question: "The legacy FTP service uses a separate control connection channel.\nWhat is the standard TCP command port for FTP?",
    answer: "21",
    acceptedAnswers: ["21", "port 21"],
    hints: {
      1: { order: 1, text: "One port below SSH (port 22).", penaltySeconds: 15 },
      2: { order: 2, text: "22 - 1.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 21.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-21",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Security",
    question: "Secure directory authentication uses LDAP over SSL (LDAPS).\nEnter the standard TCP port number for LDAPS.",
    answer: "636",
    acceptedAnswers: ["636", "port 636"],
    hints: {
      1: { order: 1, text: "Standard unencrypted LDAP is 389.", penaltySeconds: 15 },
      2: { order: 2, text: "LDAPS port has three digits: 6_6.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 636.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-22",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Routing Protocols",
    question: "Core internet routing between autonomous systems uses BGP.\nWhat is the default TCP port for Border Gateway Protocol (BGP)?",
    answer: "179",
    acceptedAnswers: ["179", "port 179"],
    hints: {
      1: { order: 1, text: "BGP router peering port.", penaltySeconds: 15 },
      2: { order: 2, text: "Three digits in the late one-hundreds.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 179.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
  {
    id: "ch-9-23",
    levelId: 9,
    difficulty: "EXPERT",
    type: "networking",
    category: "Network Security",
    question: "Domain ticket-granting authentication uses Kerberos.\nWhat is the standard port number for Kerberos authentication service?",
    answer: "88",
    acceptedAnswers: ["88", "port 88"],
    hints: {
      1: { order: 2, text: "A repeating two-digit number in the eighties.", penaltySeconds: 15 },
      2: { order: 2, text: "8 followed by 8.", penaltySeconds: 30 },
      3: { order: 3, text: "Port is 88.", penaltySeconds: 45 },
    },
    penaltySeconds: 30,
    isActive: true,
  },
];
