/**
 * Authoritative Server-Side Game Configuration for Level 4: "Row Seven"
 * 
 * SECURITY: Correct answers and internal clue metadata are stored exclusively
 * here and must NEVER be leaked or returned in client API responses.
 */

export const LEVEL_4_CONFIG = {
  levelId: 4,
  name: "Row Seven",
  location: "Auditorium / Stage Hall",
  targetObjectId: "auditorium_seat_row7",
  targetObjectDisplayName: "Row 7 Seat",
  targetPosition: [0, 0, 1.5] as const,
  scannerDetectionRadius: 6,
  clue: {
    id: "clue-4",
    levelId: 4,
    text: "The trace moves toward the central dining hall. Find what was left behind at the corner table.",
    destination: "Cafeteria",
  },
  challenge: {
    id: "ch-4",
    levelId: 4,
    type: "logic",
    question:
      "The sound technician's log under Seat 7F shows an acoustic frequency sequence: 4, 9, 19, 39, 79, ?. What is the next frequency value in the sequence?",
    // Authoritative answer — NEVER expose in any response
    answer: "159",
  },
  grantedItem: "circuit_piece",
  decoys: [
    {
      id: "auditorium_podium",
      label: "Speaker's Podium",
      message: "Microphone wires, lecture notes from a guest seminar, and an empty water bottle.",
    },
    {
      id: "auditorium_projector",
      label: "AV Control Rack",
      message: "Projector switches and video distribution amplifiers. All channels are dark.",
    },
    {
      id: "auditorium_soundboard",
      label: "Sound Mixing Console",
      message: "Master faders are pulled down. The acoustic monitor displays zero signal.",
    },
    {
      id: "auditorium_backstage_door",
      label: "Backstage Access Door",
      message: "Heavy acoustic door locked from the stage side. A sign reads: AUTHORIZED PERSONNEL ONLY.",
    },
  ],
  hints: {
    1: {
      order: 1,
      text: "Observe the relationship between each consecutive number in the sequence.",
      penaltySeconds: 15,
    },
    2: {
      order: 2,
      text: "Each term is generated by doubling the previous term and adding one: (n * 2) + 1.",
      penaltySeconds: 30,
    },
    3: {
      order: 3,
      text: "79 * 2 = 158. Add 1 to get 159.",
      penaltySeconds: 45,
    },
  } as Record<number, { order: number; text: string; penaltySeconds: number }>,
  penalties: {
    wrongAnswer: 30,
    scanner: 10,
  },
} as const;
